class_name CampRumorDB

const RUMOR_DEFAULT_RADIUS: float = 140.0

const RUMORS: Array = [
	{
		"id": "kaelen_watch_dawn",
		"preferred_visit_themes": ["training", "tense"],
		"avoided_visit_themes": ["gossip"],
		"priority": 10,
		"when": { "time_block": "dawn" },
		"speaker": "Kaelen",
		"zone_type": "watch_post",
		"text": "\"Quiet out here. Good.\"",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "darian_fire_night",
		"preferred_visit_themes": ["normal", "hopeful"],
		"priority": 8,
		"when": { "time_block": "night" },
		"speaker": "Darian",
		"zone_type": "fire",
		"text": "\"Never pass up a warm fire when you can get one.\"",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rufus_workbench_day",
		"preferred_visit_themes": ["training", "normal"],
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Rufus",
		"zone_type": "workbench",
		"text": "\"One more fix and this'll hold.\"",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "sorrel_map_day",
		"preferred_visit_themes": ["gossip", "normal"],
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Sorrel",
		"zone_type": "map_table",
		"text": "\"The roads here don't match the old charts.\"",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "liora_shrine",
		"priority": 7,
		"when": { "time_block": "day" },
		"speaker": "Liora",
		"zone_type": "shrine",
		"text": "\"A moment of peace costs nothing.\"",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "brother_alden_infirmary",
		"preferred_visit_themes": ["recovery", "somber"],
		"priority": 7,
		"when": { "time_block": "day" },
		"speaker": "Brother Alden",
		"zone_type": "infirmary",
		"text": "\"Rest and clean bandages. The rest can wait.\"",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "garrick_watch",
		"preferred_visit_themes": ["tense", "training"],
		"priority": 6,
		"when": { "time_block": "day" },
		"speaker": "Garrick Vale",
		"zone_type": "watch_post",
		"text": "\"Eyes open. Always.\"",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "sabine_wall",
		"preferred_visit_themes": ["tense", "somber"],
		"priority": 6,
		"when": { "time_block": "night" },
		"speaker": "Sabine Varr",
		"zone_type": "wall",
		"text": "\"Walls keep more than weather out.\"",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "hest_workbench",
		"preferred_visit_themes": ["training"],
		"priority": 7,
		"when": { "time_block": "day" },
		"speaker": "Hest \"Sparks\"",
		"zone_type": "workbench",
		"text": "\"Tools first. Talk later.\"",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "hest_supply",
		"priority": 6,
		"when": { "time_block": "day" },
		"speaker": "Hest \"Sparks\"",
		"zone_type": "supply",
		"text": "\"Count it twice. You'll thank me.\"",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "celia_watch_dawn_check_straps",
		"priority": 9,
		"when": { "time_block": "dawn" },
		"speaker": "Celia",
		"zone_type": "watch_post",
		"text": "Straps tight, eyes open. Same as always.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "celia_bench_dawn_restless",
		"priority": 7,
		"when": { "time_block": "dawn" },
		"speaker": "Celia",
		"zone_type": "bench",
		"text": "Sitting still feels wrong before the camp wakes.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "tariq_map_day_margins",
		"priority": 9,
		"when": { "time_block": "day" },
		"speaker": "Tariq",
		"zone_type": "map_table",
		"text": "The danger is never on the inked routes. It's in the margins.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "tariq_map_day_redraw",
		"priority": 7,
		"when": { "time_block": "day" },
		"speaker": "Tariq",
		"zone_type": "map_table",
		"text": "Every time we redraw a border, someone pays twice.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "inez_tree_night_listening",
		"priority": 9,
		"when": { "time_block": "night" },
		"speaker": "Inez",
		"zone_type": "tree_line",
		"text": "The trees complain when steel walks wrong through them.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "inez_tree_night_signs",
		"priority": 7,
		"when": { "time_block": "night" },
		"speaker": "Inez",
		"zone_type": "tree_line",
		"text": "Birds left early. That's never a kind omen.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "oren_wall_day_bracing",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Oren Pike",
		"zone_type": "wall",
		"text": "If the wall creaks now, it will scream in a storm.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "oren_workbench_day_weight",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Oren Pike",
		"zone_type": "workbench",
		"text": "Good timber complains before it fails. People don't.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "tamsin_infirmary_day_inventory",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Tamsin Reed",
		"zone_type": "infirmary",
		"text": "If I count these salves one more time, maybe no one will need them.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "tamsin_fire_night_shake",
		"preferred_visit_themes": ["recovery", "somber"],
		"priority": 7,
		"when": { "time_block": "night" },
		"speaker": "Tamsin Reed",
		"zone_type": "fire",
		"text": "Hands stop shaking faster when they're holding a mug.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "meris_shrine_day_ledger",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Sister Meris",
		"zone_type": "shrine",
		"text": "Some prayers sound too much like ledgers to trust anymore.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "meris_map_day_truth",
		"preferred_visit_themes": ["gossip", "somber"],
		"priority": 7,
		"when": { "time_block": "day" },
		"speaker": "Sister Meris",
		"zone_type": "map_table",
		"text": "Maps lie politely. Testimony lies louder.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "corvin_wagon_night_records",
		"priority": 9,
		"when": { "time_block": "night" },
		"speaker": "Corvin Ash",
		"zone_type": "wagon",
		"text": "Archives travel badly. Guilt travels better.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "corvin_shrine_night_saints",
		"priority": 8,
		"when": { "time_block": "night" },
		"speaker": "Corvin Ash",
		"zone_type": "shrine",
		"text": "Saints make convenient culprits for human choices.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "veska_wall_day_line",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Veska Moor",
		"zone_type": "wall",
		"text": "Hold the line here, or the ground decides for us.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "veska_workbench_day_shield",
		"priority": 7,
		"when": { "time_block": "day" },
		"speaker": "Veska Moor",
		"zone_type": "workbench",
		"text": "A loose strap is an invitation, not a mistake.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "hadrien_shrine_night_watch",
		"priority": 8,
		"when": { "time_block": "night" },
		"speaker": "Ser Hadrien",
		"zone_type": "shrine",
		"text": "Old oaths echo louder when the camp sleeps.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "hadrien_watch_night_regret",
		"priority": 7,
		"when": { "time_block": "night" },
		"speaker": "Ser Hadrien",
		"zone_type": "watch_post",
		"text": "The stars have watched worse marches than ours.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "maela_tree_dawn_height",
		"priority": 8,
		"when": { "time_block": "dawn" },
		"speaker": "Maela Thorn",
		"zone_type": "tree_line",
		"text": "Camp looks kinder from a little higher up.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "maela_watch_dawn_jump",
		"priority": 7,
		"when": { "time_block": "dawn" },
		"speaker": "Maela Thorn",
		"zone_type": "watch_post",
		"text": "If I fall, someone had better be watching.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "yselle_fire_night_story",
		"priority": 8,
		"when": { "time_block": "night" },
		"speaker": "Yselle Maris",
		"zone_type": "fire",
		"text": "The trick is telling the story without making ruin sound charming.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "yselle_bench_night_applause",
		"priority": 7,
		"when": { "time_block": "night" },
		"speaker": "Yselle Maris",
		"zone_type": "bench",
		"text": "No audience tonight. Good. We can breathe instead.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "nyx_supply_day_ledger",
		"preferred_visit_themes": ["gossip", "tense"],
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Nyx",
		"zone_type": "supply",
		"text": "Funny how every missing crate has a very tidy explanation.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "nyx_wagon_night_exits",
		"priority": 8,
		"when": { "time_block": "night" },
		"speaker": "Nyx",
		"zone_type": "wagon",
		"text": "Count the exits now, regret less later.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "nyx_workbench_day_traps",
		"priority": 7,
		"when": { "time_block": "day" },
		"speaker": "Nyx",
		"zone_type": "workbench",
		"text": "Half the traps in this camp are paperwork, not wire.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "kaelen_watch_dawn_familiar_listener",
		"priority": 11,
		"when": { "time_block": "dawn" },
		"speaker": "Kaelen",
		"listener": "Celia",
		"min_familiarity": 1,
		"zone_type": "watch_post",
		"nearby_units": ["Celia"],
		"text": "She's sharp now. I don't need to repeat myself.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "sorrel_map_day_familiar_listener",
		"priority": 10,
		"when": { "time_block": "day" },
		"speaker": "Sorrel",
		"listener": "Tariq",
		"min_familiarity": 1,
		"zone_type": "map_table",
		"nearby_units": ["Tariq"],
		"text": "When Tariq goes quiet, it means the numbers finally agree.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "nyx_workbench_day_recent_listener",
		"priority": 10,
		"when": { "time_block": "day" },
		"speaker": "Nyx",
		"listener": "Hest \"Sparks\"",
		"recent_within_visits": 1,
		"zone_type": "workbench",
		"nearby_units": ["Hest \"Sparks\""],
		"text": "If Sparks says \"small adjustment,\" I stay close anyway.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "garrick_wall_day_tension_listener",
		"priority": 9,
		"when": { "time_block": "day" },
		"speaker": "Garrick Vale",
		"listener": "Sabine Varr",
		"min_tension": 1,
		"zone_type": "wall",
		"nearby_units": ["Sabine Varr"],
		"text": "Clear words save time. Today we're short on time.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "tamsin_fire_night_speaker_variant",
		"priority": 8,
		"when": { "time_block": "night" },
		"speaker": "Tamsin Reed",
		"zone_type": "fire",
		"text": "Quiet cups and hot stew can hold a camp together.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "tariq_map_day_speaker_variant",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Tariq",
		"zone_type": "map_table",
		"text": "Some roads improve once people stop pretending they're straight.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_tamsin_hopeful_fire",
		"priority": 9,
		"when": { "time_block": "night" },
		"moods": ["hopeful"],
		"speaker": "Tamsin Reed",
		"zone_type": "fire",
		"text": "Tonight the fire sounds like breathing, not alarms.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_kaelen_tense_watch",
		"priority": 10,
		"when": { "time_block": "dawn" },
		"moods": ["tense"],
		"speaker": "Kaelen",
		"zone_type": "watch_post",
		"text": "Short checks, sharp answers. No one drifts today.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_liora_somber_infirmary",
		"priority": 9,
		"when": { "time_block": "day" },
		"moods": ["somber"],
		"speaker": "Liora",
		"zone_type": "infirmary",
		"text": "Quiet hands help more than brave words sometimes.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_nyx_hest_tense_listener",
		"preferred_visit_themes": ["tense"],
		"priority": 10,
		"when": { "time_block": "day" },
		"moods": ["tense"],
		"speaker": "Nyx",
		"listener": "Hest \"Sparks\"",
		"nearby_units": ["Hest \"Sparks\""],
		"zone_type": "workbench",
		"text": "Sparks jokes louder when she's worried. I count that as warning.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_tamsin_infirmary_injured",
		"priority": 10,
		"when": { "time_block": "day" },
		"speaker": "Tamsin Reed",
		"requires_injured_speaker": true,
		"zone_type": "infirmary",
		"text": "I'm not stopping. I'm just changing bandages while I stand.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_branik_fire_fatigued",
		"priority": 9,
		"when": { "time_block": "night" },
		"speaker": "Branik",
		"requires_fatigued_speaker": true,
		"zone_type": "fire",
		"text": "If your hands are shaking, hold the bowl with both. No shame in that.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_kaelen_watch_injured",
		"priority": 10,
		"when": { "time_block": "dawn" },
		"speaker": "Kaelen",
		"requires_injured_speaker": true,
		"zone_type": "watch_post",
		"text": "I can still hold a line. Just don't ask me to sprint to prove it.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_liora_alden_fatigued_listener",
		"priority": 10,
		"when": { "time_block": "day" },
		"speaker": "Liora",
		"listener": "Brother Alden",
		"requires_fatigued_listener": true,
		"nearby_units": ["Brother Alden"],
		"zone_type": "infirmary",
		"text": "Alden keeps saying he's fine. His eyes disagree.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_pell_watch_dawn_focus",
		"priority": 8,
		"when": { "time_block": "dawn" },
		"speaker": "Pell Rowan",
		"zone_type": "watch_post",
		"text": "If I can hold this line at dawn, I can hold it when it matters.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "rumor_mira_tree_night_memory",
		"priority": 8,
		"when": { "time_block": "night" },
		"speaker": "Mira Ashdown",
		"zone_type": "tree_line",
		"text": "I map the dark by sound now. It helps me sleep later.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_rufus_wall_day_bolts",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Rufus",
		"zone_type": "wall",
		"text": "Loose bolts are a sermon nobody wants to hear twice.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "rumor_yselle_bench_night_mask",
		"priority": 8,
		"when": { "time_block": "night" },
		"speaker": "Yselle Maris",
		"zone_type": "bench",
		"text": "A calm voice is armor. Good armor still needs mending.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_inez_watch_dawn_scent",
		"priority": 8,
		"when": { "time_block": "dawn" },
		"speaker": "Inez",
		"zone_type": "watch_post",
		"text": "If the wind tastes like iron before sunrise, ready your bow first.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_corvin_map_day_erasures",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Corvin Ash",
		"zone_type": "map_table",
		"text": "The most honest parts of history are usually the ones scraped out.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_hadrien_wall_dawn_count",
		"priority": 8,
		"when": { "time_block": "dawn" },
		"speaker": "Ser Hadrien",
		"zone_type": "wall",
		"text": "Count the living at dawn. The fallen are patient.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_maela_wall_day_restless",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Maela Thorn",
		"zone_type": "wall",
		"text": "If I'm pacing, it's because the ground keeps pretending it's enough.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_veska_watch_night_roots",
		"priority": 8,
		"when": { "time_block": "night" },
		"speaker": "Veska Moor",
		"zone_type": "watch_post",
		"text": "Plant your feet like roots. Panic hates roots.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_meris_infirmary_day_mercy",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Sister Meris",
		"zone_type": "infirmary",
		"text": "Mercy without record becomes myth; record without mercy becomes cruelty.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_pell_workbench_day_repetition",
		"preferred_visit_themes": ["training"],
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Pell Rowan",
		"zone_type": "workbench",
		"text": "Drill it until your hands stop asking permission.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "rumor_mira_watch_dawn_stillness",
		"preferred_visit_themes": ["training"],
		"priority": 8,
		"when": { "time_block": "dawn" },
		"speaker": "Mira Ashdown",
		"zone_type": "watch_post",
		"text": "Stillness is work. People only notice the shot after.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "rumor_progress_early_pell_watch",
		"priority": 9,
		"when": { "time_block": "dawn" },
		"min_progress_level": 2,
		"max_progress_level": 6,
		"speaker": "Pell Rowan",
		"zone_type": "watch_post",
		"text": "Greyspire still feels borrowed. So I check my post like I have to earn it.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "rumor_progress_mid_meris_shrine",
		"priority": 9,
		"when": { "time_block": "night" },
		"min_progress_level": 9,
		"max_progress_level": 13,
		"speaker": "Sister Meris",
		"zone_type": "shrine",
		"text": "After enough victories, people call caution cynicism. I prefer caution.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_progress_late_hadrien_wall",
		"preferred_visit_themes": ["somber"],
		"priority": 10,
		"when": { "time_block": "night" },
		"min_progress_level": 16,
		"speaker": "Ser Hadrien",
		"zone_type": "wall",
		"text": "The nearer the end, the quieter discipline must become.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "branik_cook_dawn_kettle",
		"preferred_visit_themes": ["normal", "recovery"],
		"priority": 6,
		"when": { "time_block": "dawn" },
		"speaker": "Branik",
		"zone_type": "cook_area",
		"text": "Kettle's already on. Worry can wait until after breakfast.",
		"text_variants": [
			"Water's hot. Whatever you're carrying, let it soften with the steam, not your spine.",
			"Bread'll be ready soon. Save the heavy talk for when there's crumbs on the plate.",
		],
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "branik_supply_day_portions",
		"priority": 5,
		"when": { "time_block": "day" },
		"speaker": "Branik",
		"zone_type": "supply",
		"text": "If we portion it right, nobody goes hungry tonight.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "darian_bench_day_collar",
		"preferred_visit_themes": ["normal", "hopeful"],
		"priority": 7,
		"when": { "time_block": "day" },
		"speaker": "Darian",
		"zone_type": "bench",
		"text": "Dust on the collar, blood on the boots. A perfectly honest day.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "darian_wagon_night_hush",
		"priority": 7,
		"when": { "time_block": "night" },
		"speaker": "Darian",
		"zone_type": "wagon",
		"text": "Funny how wagons creak louder when everyone is trying to be brave quietly.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rufus_fire_night_bolts",
		"priority": 7,
		"when": { "time_block": "night" },
		"speaker": "Rufus",
		"zone_type": "fire",
		"text": "Hot meal, dry hands, tightened bolts. Close enough to luxury.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "inez_wall_dawn_tracks",
		"priority": 8,
		"when": { "time_block": "dawn" },
		"speaker": "Inez",
		"zone_type": "wall",
		"text": "Fresh mud below the wall. Rabbit, not raider.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "tariq_wagon_night_ledgers",
		"priority": 7,
		"when": { "time_block": "night" },
		"speaker": "Tariq",
		"zone_type": "wagon",
		"text": "Every chest has a lock. The interesting ones have two.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "alden_watch_dawn_breath",
		"priority": 7,
		"when": { "time_block": "dawn" },
		"speaker": "Brother Alden",
		"zone_type": "watch_post",
		"text": "Cold air, steady hands, one breath at a time. That is enough.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "oren_supply_day_rope",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Oren Pike",
		"zone_type": "supply",
		"text": "If the rope frays here, it fails somewhere expensive later.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "yselle_bench_night_silence",
		"preferred_visit_themes": ["recovery", "somber"],
		"avoided_visit_themes": ["gossip"],
		"priority": 7,
		"when": { "time_block": "night" },
		"speaker": "Yselle Maris",
		"zone_type": "bench",
		"text": "A quiet bench can do almost as much for morale as a good song.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "yselle_wagon_day_ribbon",
		"priority": 6,
		"when": { "time_block": "day" },
		"speaker": "Yselle Maris",
		"zone_type": "wagon",
		"text": "A bright ribbon on a drab wagon tells tired people we still remember color.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "sabine_supply_day_inventory",
		"priority": 8,
		"when": { "time_block": "day" },
		"min_progress_level": 5,
		"speaker": "Sabine Varr",
		"zone_type": "supply",
		"text": "Order is not glamour. Order is why camp still functions by sundown.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "corvin_bench_night_sleep",
		"preferred_visit_themes": ["somber", "recovery"],
		"priority": 7,
		"when": { "time_block": "night" },
		"speaker": "Corvin Ash",
		"zone_type": "bench",
		"text": "Sleep is easier near a lantern. It lies more kindly than the dark.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "veska_supply_day_stacks",
		"priority": 7,
		"when": { "time_block": "day" },
		"speaker": "Veska Moor",
		"zone_type": "supply",
		"text": "Stack the heavy crates low. Gravity already has enough allies.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "maela_watch_dawn_roofline",
		"priority": 7,
		"when": { "time_block": "dawn" },
		"speaker": "Maela Thorn",
		"zone_type": "watch_post",
		"text": "Best part of dawn is beating everyone else to the view.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "maela_tree_day_laps",
		"priority": 7,
		"when": { "time_block": "day" },
		"speaker": "Maela Thorn",
		"zone_type": "tree_line",
		"text": "Did three laps around camp. Would have done four if the wall were prettier.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "liora_fire_night_teakettle",
		"priority": 7,
		"when": { "time_block": "night" },
		"min_progress_level": 3,
		"speaker": "Liora",
		"zone_type": "fire",
		"text": "Tea first, then prayer. People hear comfort better that way.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "sorrel_shrine_night_margins",
		"priority": 6,
		"when": { "time_block": "night" },
		"speaker": "Sorrel",
		"zone_type": "shrine",
		"text": "Someone left notes in the prayer book margins. Thoughtful notes, too.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "pell_supply_day_straps",
		"priority": 7,
		"when": { "time_block": "day" },
		"max_progress_level": 4,
		"speaker": "Pell Rowan",
		"zone_type": "supply",
		"text": "If the straps are sorted before drill, that still counts as readiness.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "garrick_map_day_markers",
		"priority": 7,
		"when": { "time_block": "day" },
		"min_progress_level": 5,
		"speaker": "Garrick Vale",
		"zone_type": "map_table",
		"text": "Move the markers after every patrol. Assumptions kill faster than arrows.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "hadrien_watch_night_names",
		"priority": 8,
		"when": { "time_block": "night" },
		"min_progress_level": 12,
		"speaker": "Ser Hadrien",
		"zone_type": "watch_post",
		"text": "Keep the names of the living close. The dead have already claimed enough company.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "meris_infirmary_day_linen",
		"priority": 7,
		"when": { "time_block": "day" },
		"min_progress_level": 7,
		"speaker": "Sister Meris",
		"zone_type": "infirmary",
		"text": "Fold the linen flat. Carelessness spreads farther here than blood.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "nyx_wagon_night_lock",
		"priority": 7,
		"when": { "time_block": "night" },
		"speaker": "Nyx",
		"zone_type": "wagon",
		"text": "Relax. I only checked the lock because I like us having supplies tomorrow.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "mira_fire_night_count",
		"priority": 7,
		"when": { "time_block": "night" },
		"speaker": "Mira Ashdown",
		"zone_type": "fire",
		"text": "I count heads at the fire without meaning to. I stop when the number holds.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "tamsin_bench_night_lists",
		"priority": 7,
		"when": { "time_block": "night" },
		"speaker": "Tamsin Reed",
		"zone_type": "bench",
		"text": "If I put the lists in order now, morning feels a little less dangerous.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "rumor_theme_recovery_alden_bench_dawn",
		"priority": 9,
		"when": { "time_block": "dawn" },
		"speaker": "Brother Alden",
		"zone_type": "bench",
		"preferred_visit_themes": ["recovery"],
		"text": "Five minutes seated will not undo your conscience—but it might keep your hands steady for the rest.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_theme_recovery_sabine_wall_day",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Sabine Varr",
		"zone_type": "wall",
		"preferred_visit_themes": ["recovery"],
		"text": "Shoulder's stiff, not broken. I still rotate the post—just slower, and with fewer apologies.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "rumor_theme_gossip_corvin_bench_night",
		"priority": 8,
		"when": { "time_block": "night" },
		"speaker": "Corvin Ash",
		"zone_type": "bench",
		"preferred_visit_themes": ["gossip"],
		"text": "Half the camp swears someone \"borrowed\" a lantern that never existed. I love a tidy contradiction.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_theme_gossip_tariq_wagon_day",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Tariq",
		"zone_type": "wagon",
		"preferred_visit_themes": ["gossip", "tense"],
		"text": "They say the courier took the long road to avoid gossip. All that proves is the rumor beat him home.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "rumor_theme_training_veska_wall_day",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Veska Moor",
		"zone_type": "wall",
		"preferred_visit_themes": ["training"],
		"text": "Raise shield, breathe, reset. Boredom is how bodies learn to stop lying.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "rumor_theme_hopeful_liora_cook_day",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Liora",
		"zone_type": "cook_area",
		"preferred_visit_themes": ["hopeful"],
		"text": "Branik let me steal the pot for tea. I promised not to turn it into a sermon. He said that was unlikely.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_theme_somber_hadrien_shrine_night",
		"priority": 9,
		"when": { "time_block": "night" },
		"speaker": "Ser Hadrien",
		"zone_type": "shrine",
		"preferred_visit_themes": ["somber"],
		"text": "Some names are easier to carry than to speak aloud. Silence is not always cowardice—sometimes it is weight.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_theme_somber_mira_tree_night",
		"priority": 8,
		"when": { "time_block": "night" },
		"speaker": "Mira Ashdown",
		"zone_type": "tree_line",
		"preferred_visit_themes": ["somber"],
		"text": "The dark made a liar of me once. Tonight it only had to be empty—and that was work enough.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_theme_tense_celia_watch_day",
		"priority": 9,
		"when": { "time_block": "day" },
		"speaker": "Celia",
		"zone_type": "watch_post",
		"preferred_visit_themes": ["tense"],
		"text": "North peg's rattling again—I'll tag it on the next sweep. Save the debrief for after; the ridge doesn't care who's eloquent.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_theme_tense_garrick_map_day",
		"priority": 9,
		"when": { "time_block": "day" },
		"speaker": "Garrick Vale",
		"zone_type": "map_table",
		"preferred_visit_themes": ["tense"],
		"text": "That old route stays inked until I scrape it off myself—no squad marches on another officer's souvenir memory.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_theme_normal_oren_supply_day",
		"priority": 7,
		"when": { "time_block": "day" },
		"speaker": "Oren Pike",
		"zone_type": "supply",
		"preferred_visit_themes": ["normal"],
		"avoided_visit_themes": ["gossip"],
		"text": "Inventory is boring until it isn't. Today it is still boring—good sign.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "rumor_theme_normal_darian_wagon_day",
		"priority": 7,
		"when": { "time_block": "day" },
		"speaker": "Darian",
		"zone_type": "wagon",
		"preferred_visit_themes": ["normal", "hopeful"],
		"text": "Laundry drying, hinges oiled, drama postponed. A functioning camp is its own performance.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "rumor_theme_gossip_nyx_bench_day",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Nyx",
		"zone_type": "bench",
		"preferred_visit_themes": ["gossip"],
		"text": "Someone \"definitely\" saw a rider. Funny how certainty grows when nobody wants to fetch a lantern.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "rumor_theme_recovery_tamsin_infirmary_quiet",
		"priority": 9,
		"when": { "time_block": "night" },
		"speaker": "Tamsin Reed",
		"zone_type": "infirmary",
		"preferred_visit_themes": ["recovery"],
		"text": "Quiet tent tonight. I do not trust good luck, but I will borrow it while it lasts.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_theme_somber_meris_infirmary_night",
		"priority": 8,
		"when": { "time_block": "night" },
		"speaker": "Sister Meris",
		"zone_type": "infirmary",
		"preferred_visit_themes": ["somber"],
		"text": "We saved what we could. File the rest without turning it into a speech—some losses refuse polish.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_theme_gossip_liora_shrine_day",
		"priority": 7,
		"when": { "time_block": "day" },
		"speaker": "Liora",
		"zone_type": "shrine",
		"preferred_visit_themes": ["gossip"],
		"text": "Fresh violets on the rail—someone's heart spoke louder than their kneecaps. I'll leave water for both.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_theme_tense_inez_watch_dawn",
		"priority": 9,
		"when": { "time_block": "dawn" },
		"speaker": "Inez",
		"zone_type": "watch_post",
		"preferred_visit_themes": ["tense"],
		"text": "You hear that snap? Too sharp for deer. Wake the next line before curiosity does it for you.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "rumor_theme_training_hest_workbench_day",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Hest \"Sparks\"",
		"zone_type": "workbench",
		"preferred_visit_themes": ["training"],
		"text": "Same procedure, tenth time. If you're bored, you're finally doing it right enough to be safe.",
		"once_per_visit": false,
		"radius": 140.0,
	},
	{
		"id": "rumor_theme_recovery_branik_fire_night",
		"priority": 6,
		"when": { "time_block": "night" },
		"speaker": "Branik",
		"zone_type": "fire",
		"preferred_visit_themes": ["recovery"],
		"text": "Second helpings for anyone still shaking. Hunger lies louder than courage after a long march.",
		"once_per_visit": true,
		"radius": 140.0,
	},
	{
		"id": "rumor_theme_hopeful_yselle_fire_night",
		"priority": 8,
		"when": { "time_block": "night" },
		"speaker": "Yselle Maris",
		"zone_type": "fire",
		"preferred_visit_themes": ["hopeful"],
		"text": "Tonight nobody has to earn their rest with a story. Sit, eat, be unremarkable on purpose.",
		"once_per_visit": true,
		"radius": 140.0,
	},
]

static func get_all_rumors() -> Array:
	return RUMORS.duplicate()

static func when_matches(rumor: Dictionary, context: Dictionary) -> bool:
	var when_dict: Variant = rumor.get("when", {})
	if not (when_dict is Dictionary):
		pass
	else:
		for k in (when_dict as Dictionary).keys():
			var expected = (when_dict as Dictionary).get(k)
			if not context.has(k):
				return false
			if str(context.get(k)) != str(expected):
				return false
	if rumor.has("moods"):
		var moods_v: Variant = rumor.get("moods", [])
		if moods_v is Array:
			var want_mood: String = str(context.get("camp_mood", "normal")).strip_edges().to_lower()
			var allowed: Array = moods_v
			var matched: bool = false
			for m in allowed:
				if str(m).strip_edges().to_lower() == want_mood:
					matched = true
					break
			if not matched:
				return false
	if not _story_progress_matches(rumor, context):
		return false
	return true

static func _story_progress_matches(entry: Dictionary, context: Dictionary) -> bool:
	var progress_level: int = int(context.get("progress_level", 0))
	var min_level: int = int(entry.get("min_progress_level", -1))
	if min_level >= 0 and progress_level < min_level:
		return false
	var max_level: int = int(entry.get("max_progress_level", -1))
	if max_level >= 0 and progress_level > max_level:
		return false
	var flags_v: Variant = context.get("story_flags", {})
	var story_flags: Dictionary = flags_v if flags_v is Dictionary else {}
	var req_v: Variant = entry.get("required_story_flags", [])
	if req_v is Array:
		for token_v in (req_v as Array):
			var token: String = str(token_v).strip_edges()
			if token == "":
				continue
			if not bool(story_flags.get(token, false)):
				return false
	var block_v: Variant = entry.get("blocked_story_flags", [])
	if block_v is Array:
		for token_v2 in (block_v as Array):
			var token2: String = str(token_v2).strip_edges()
			if token2 == "":
				continue
			if bool(story_flags.get(token2, false)):
				return false
	return true
