class_name CampPairSceneDB

const PAIR_SCENES: Array = [
	{
		"id": "pair_kaelen_nyx_greyspire_watch",
		"unit_a": "Kaelen",
		"unit_b": "Nyx",
		"title": "Edge of the Firelight",
		"text": "Kaelen stands at the camp’s edge, studying Greyspire’s outline. Nyx drifts up beside him, hands in their pockets.\n\n\"Counting ghosts?\" Nyx asks.\n\"Counting walls,\" Kaelen replies. \"And the fools who think they’re enough.\"\nNyx snorts. \"Walls keep people out. Debt keeps them in.\"\nHe glances at them. \"You’d know.\"\n\"You would too,\" they shoot back, softer than their words. For a moment, the two of them share the same tired horizon.",
		"threshold_a": "trusted",
		"threshold_b": "trusted",
		"requires_flags": ["greyspire_hub_established"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 50,
	},
	{
		"id": "pair_kaelen_liora_sanctum_fallout",
		"unit_a": "Kaelen",
		"unit_b": "Liora",
		"title": "Ash and Incense",
		"text": "Liora stands near a broken shrine, thumb tracing the edge of a cracked icon. \"We used to light incense here for the sick,\" she says.\n\"And now?\" Kaelen asks.\n\"Now it smells like fear and paperwork,\" she answers, half a laugh, half a sob. \"I used to believe we were purifying something.\"\nKaelen rests a hand on the stone. \"We were. Just not always the right thing.\" He lets the silence sit. \"You’re trying again. That’s more than most orders ever manage.\"",
		"threshold_a": "trusted",
		"threshold_b": "trusted",
		"requires_flags": ["greyspire_hub_established"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 50,
	},
	{
		"id": "pair_nyx_sorrel_market_whispers",
		"unit_a": "Nyx",
		"unit_b": "Sorrel",
		"title": "Margins and Alleyways",
		"text": "Sorrel flips through a notebook, muttering about redacted ledgers from the Market of Masks. Nyx lounges nearby on a crate.\n\n\"You don’t need a cipher,\" Nyx says. \"You need to follow who got paid to look surprised.\"\nSorrel tilts their head. \"You have an instinct for where systems hide rot.\"\n\"No,\" Nyx replies. \"I have scars from being the rot they hired, once. You read the margins; I remember the alleys they walked through to write them.\"",
		"threshold_a": "trusted",
		"threshold_b": "known",
		"requires_flags": ["market_of_masks_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 50,
	},
	{
		"id": "pair_branik_tamsin_kitchen_truce",
		"unit_a": "Branik",
		"unit_b": "Tamsin Reed",
		"title": "Kitchen Truce",
		"text": "Tamsin is reorganizing herbs on a cramped camp shelf. Branik ducks into the tent, arms full of vegetables.\n\n\"You’re alphabetizing thyme again,\" he observes.\n\"It was chaos,\" she protests. \"Someone put feverfew next to the smoked salt.\"\nHe smiles. \"Chaos is when you’re trying to cook with a pot that’s also remembering being a helmet. This is… care.\" He starts chopping. \"Tell you what. You keep breathing in order. I’ll keep making sure you get to.\"",
		"threshold_a": "known",
		"threshold_b": "known",
		"requires_flags": ["greyspire_hub_established"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 40,
	},
	{
		"id": "pair_meris_corvin_after_echoes",
		"unit_a": "Sister Meris",
		"unit_b": "Corvin Ash",
		"title": "Witnesses",
		"text": "Meris and Corvin stand near the ward-stakes, watching the last shimmer of ritual fade.\n\n\"You knew what they were doing in those lower halls,\" Meris says quietly.\n\"I knew enough to be afraid of the files they didn’t let me see,\" Corvin replies. \"That’s usually where the real theology lives.\"\nShe grimaces. \"I signed off on some of those closures. Stamped my name over people I never met.\"\nCorvin’s gaze is level. \"Then you are here, watching what happens when we try to do better. That is more than most archivists of atrocity ever manage.\"",
		"threshold_a": "trusted",
		"threshold_b": "trusted",
		"requires_flags": ["echoes_of_the_order_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 60,
	},
	{
		"id": "pair_hadrien_kaelen_order_shadows",
		"unit_a": "Ser Hadrien",
		"unit_b": "Kaelen",
		"title": "Old Oaths, New Wounds",
		"text": "Hadrien’s spectral form stands beside Kaelen as the camp settles.\n\n\"You wear our colors badly,\" the ghost knight says. \"That is not an insult.\"\nKaelen snorts. \"I’ve been trying to outlive them for years. Doesn’t seem I’ve done a convincing job.\"\n\"You question what we once called duty,\" Hadrien replies. \"That may be the only way the Dawn deserves any echo at all.\"\nKaelen’s shoulders sag a fraction. \"Funny. I spent half my life trying to be you, and the other half trying to escape what that cost.\"",
		"threshold_a": "trusted",
		"threshold_b": "trusted",
		"requires_flags": ["echoes_of_the_order_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 60,
	},
	{
		"id": "pair_darian_sabine_after_famine",
		"unit_a": "Darian",
		"unit_b": "Sabine Varr",
		"title": "Ledgers and Lives",
		"text": "Sabine reviews supply tallies while Darian lounges nearby, unusually quiet.\n\n\"Your numbers are wrong,\" she says eventually.\n\"Impossible,\" he drawls. \"I was there when they starved those districts. I know exactly how many mouths we failed.\"\nShe looks up, eyes sharp. \"I meant the part where you keep subtracting yourself from the reckoning. You were there. You are here. That changes the equation.\" For once, he has no clever answer.",
		"threshold_a": "trusted",
		"threshold_b": "trusted",
		"requires_flags": ["market_of_masks_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 50,
	},
	{
		"id": "pair_oren_hest_camp_inventions",
		"unit_a": "Oren Pike",
		"unit_b": "Hest \"Sparks\"",
		"title": "Structural Integrity",
		"text": "Hest proudly unveils a jury-rigged contraption near the supply tent. Oren stares at it like it insulted his ancestors.\n\n\"It works,\" Hest insists.\n\"So does falling off a roof,\" Oren replies. \"Once.\"\nThey grin. \"You worry too much about what happens after. I worry about making it go boom in the right direction.\"\nHe sighs, stepping closer. \"Fine. We’ll make sure your ‘right direction’ doesn’t include our food stores. Move it three paces left and add a brace. Then maybe we both sleep.\"",
		"threshold_a": "known",
		"threshold_b": "known",
		"requires_flags": ["greyspire_hub_established"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 40,
	},
	{
		"id": "pair_mira_pell_after_emberwood",
		"unit_a": "Mira Ashdown",
		"unit_b": "Pell Rowan",
		"title": "Targets",
		"text": "Pell practices thrusts at the edge of camp, movements stiff with effort. Mira watches from a fallen log, bow across her lap.\n\n\"You’re aiming at the wrong thing,\" she says.\nHe startles. \"I’m… trying to get the form right.\"\n\"Form’s fine,\" Mira replies. \"But you keep staring at where a song would put the enemy. Not where they’d actually be.\" She stands, adjusts his stance a fraction. \"Real targets flinch. Miss sometimes. So do we. That’s the part we live with, not polish.\"",
		"threshold_a": "known",
		"threshold_b": "known",
		"requires_flags": ["greyspire_hub_established"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 40,
	},
	{
		"id": "pair_veska_rufus_ramparts",
		"unit_a": "Veska Moor",
		"unit_b": "Rufus",
		"title": "Holding the Line",
		"text": "Veska leans on her shield near the rampart while Rufus checks the integrity of a hastily-built barricade.\n\n\"You build it like you expect it to be hit,\" she notes.\n\"Because it will be,\" he grunts. \"Question is whether it breaks before we do.\"\nShe considers that. \"Good walls are honest. If they fail, you see it. People… fail quieter.\" He nods once. \"That’s why I like walls. And shields. They don’t pretend.\"",
		"threshold_a": "known",
		"threshold_b": "known",
		"requires_flags": ["greyspire_hub_established"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 40,
	},
		{
		"id": "pair_celia_liora_lantern_oil",
		"unit_a": "Celia",
		"unit_b": "Liora",
		"title": "Lantern Oil",
		"text": "Liora is trimming a lamp wick with painstaking care when Celia stops beside her.\n\n\"You do that like a drill,\" Celia says.\n\"And you stand like one even when no one is judging you,\" Liora replies, then winces at her own sharpness. Celia almost smiles.\n\"Old habits.\"\nLiora sets the lantern down between them. \"Then let this be one too. Sit. Warmth is not indiscipline.\"\nAfter a pause, Celia does.",
		"threshold_a": "known",
		"threshold_b": "known",
		"requires_flags": ["greyspire_hub_established"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 40,
	},
	{
		"id": "pair_alden_tamsin_night_rounds",
		"unit_a": "Brother Alden",
		"unit_b": "Tamsin Reed",
		"title": "Night Rounds",
		"text": "Tamsin is halfway through checking bandages for the second time when Alden appears with a kettle.\n\n\"You missed your own tea,\" he says.\n\"I was busy making sure everyone else kept their blood inside,\" she mutters.\nAlden offers the cup without ceremony. \"A noble cause. Still easier with both hands steady.\"\nShe takes it, embarrassed. \"Do you always do this?\"\n\"Only for people who mistake exhaustion for duty,\" he says gently. \"Which, to be fair, describes half this camp.\"",
		"threshold_a": "known",
		"threshold_b": "known",
		"requires_flags": ["greyspire_hub_established"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 40,
	},
	{
		"id": "pair_nyx_hest_fuse_discipline",
		"unit_a": "Nyx",
		"unit_b": "Hest \"Sparks\"",
		"title": "Fuse Discipline",
		"text": "Hest is crouched over a string of experimental fuses when Nyx appears out of nowhere and snips one with a knife.\n\n\"Rude,\" Hest says.\n\"Alive,\" Nyx corrects. \"You braided three burn rates together and called it optimism.\"\nHest grins. \"You noticed.\"\nNyx pockets the cut fuse. \"I notice every future fire in a five-tent radius. Try being predictable enough to survive.\" They hand the fuse back a moment later. \"Shorter line. Better angle. Then maybe it only terrifies the right people.\"",
		"threshold_a": "known",
		"threshold_b": "known",
		"requires_flags": ["greyspire_hub_established"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 40,
	},
	{
		"id": "pair_rufus_oren_honest_weight",
		"unit_a": "Rufus",
		"unit_b": "Oren Pike",
		"title": "Honest Weight",
		"text": "Rufus drops a box of shot beside Oren’s workbench with a grunt.\n\n\"Too heavy for one hinge,\" Oren says without looking up.\n\"Then the hinge should complain to whoever designed it,\" Rufus replies.\nOren snorts despite himself and checks the bracket. \"You dock men solve everything by swearing at load-bearing surfaces.\"\n\"Only because load-bearing surfaces are usually more honest than officers,\" Rufus says.\nThat earns him a short, surprised laugh. \"Fair,\" Oren admits. \"Pass me the brace.\"",
		"threshold_a": "known",
		"threshold_b": "known",
		"requires_flags": ["greyspire_hub_established"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 40,
	},
	{
		"id": "pair_tariq_sorrel_footnotes",
		"unit_a": "Tariq",
		"unit_b": "Sorrel",
		"title": "Footnotes",
		"text": "Sorrel has spread notes across a crate in a pattern only they understand. Tariq glances over them and sighs.\n\n\"You annotate like a man laying traps for future scholars,\" he says.\n\"That is because future scholars are dangerous,\" Sorrel replies brightly.\nTariq rubs his temple. \"Wonderful. I was hoping you’d say something reassuringly unhinged.\"\nSorrel points to a margin. \"This symbol was altered to conceal intent.\"\nHe leans closer despite himself. \"Yes,\" he murmurs. \"That is exactly how respectable people commit crimes in libraries.\"",
		"threshold_a": "known",
		"threshold_b": "known",
		"requires_flags": [],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 40,
	},
	{
		"id": "pair_tariq_nyx_market_smoke",
		"unit_a": "Tariq",
		"unit_b": "Nyx",
		"title": "Smoke in the Margins",
		"text": "Tariq taps a line in Sorrel’s copied margin-notes while Nyx watches the camp road like it might try to sneak past unpaid.\n\n\"The Market didn’t invent lies,\" Tariq says. \"It franchised them. Same face behind every stall if you know where to look.\"\nNyx exhales through their teeth. \"And the camp?\"\n\"The camp wants a moral,\" he replies. \"Morals are cheap. Consequences are not.\"\nThey nod once—grudging respect, not comfort. \"Then we keep selling miser-words. Cold. Short. Too boring to decorate.\"\nTariq almost smiles. \"Boring survives longer than clever. Clever gets people followed home.\"\n\"Yeah,\" Nyx says softly. \"I remember the doors.\"",
		"threshold_a": "trusted",
		"threshold_b": "trusted",
		"requires_flags": ["market_of_masks_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 48,
	},
	{
		"id": "pair_yselle_darian_after_applause",
		"unit_a": "Yselle Maris",
		"unit_b": "Darian",
		"title": "After the Applause",
		"text": "Yselle adjusts a ribbon at her wrist while Darian watches the fire as if it owes him money.\n\n\"You do brood attractively,\" Yselle says.\n\"And you perform sincerity with unnerving precision,\" he replies.\nShe arches a brow. \"Perform? Darling, sometimes grace is simply the least ugly way to survive a room.\"\nThat takes the smile out of him. \"Yes,\" Darian says softly. \"I know.\"\nFor a moment, the two of them sit with the shared exhaustion of people who learned elegance under bad conditions.",
		"threshold_a": "known",
		"threshold_b": "known",
		"requires_flags": ["market_of_masks_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 45,
	},
	{
		"id": "pair_inez_maela_sky_and_root",
		"unit_a": "Inez",
		"unit_b": "Maela Thorn",
		"title": "Sky and Root",
		"text": "Maela drops lightly from a wagon roof and nearly startles Inez, who was listening to the tree line.\n\n\"You hover like a bad omen,\" Inez says.\n\"You make that sound glamorous,\" Maela grins. Then, seeing Inez remain serious, she softens. \"Sorry. What did you hear?\"\n\"Wind shifting against disturbed ground,\" Inez says. \"Someone passed through there earlier. Not one of ours.\"\nMaela looks toward the dark. \"You listen down. I listen far.\"\nInez nods once. \"Good. Then between us, perhaps this camp gets to sleep.\"",
		"threshold_a": "known",
		"threshold_b": "known",
		"requires_flags": [],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 40,
	},
	{
		"id": "pair_celia_veska_what_holding_costs",
		"unit_a": "Celia",
		"unit_b": "Veska Moor",
		"title": "What Holding Costs",
		"text": "Celia is tightening the straps on her armor when Veska sets her shield down beside the bench.\n\n\"You keep pulling them tighter after every bad day,\" Veska observes.\nCelia’s hands still. \"It helps.\"\n\"No,\" Veska says. \"It hurts in a familiar way. Different thing.\"\nCelia looks at her sharply, then away. Veska rests a hand on the rim of her shield. \"Standing firm isn’t the same as making yourself smaller to do it. Took me too long to learn that.\" \nThe silence that follows is not easy, but it is understood.",
		"threshold_a": "trusted",
		"threshold_b": "known",
		"requires_flags": ["dawnkeep_siege_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 50,
	},
	{
		"id": "pair_garrick_inez_border_marks",
		"unit_a": "Garrick Vale",
		"unit_b": "Inez",
		"title": "Border Marks",
		"text": "Garrick studies a map scratched into the dirt while Inez kneels nearby, marking routes with bits of twig.\n\n\"That path cuts across disputed land,\" Garrick says.\n\"Disputed by whom?\" Inez asks without looking up. \"The trees were here first.\"\nHe exhales through his nose. \"By men with banners and enough soldiers to make the argument tedious.\"\nInez presses another marker into the soil. \"Then let them be tedious somewhere else. We need ground that keeps people alive, not speeches loyal to dead borders.\"\nGarrick watches her work, then quietly shifts his map to match.",
		"threshold_a": "trusted",
		"threshold_b": "known",
		"requires_flags": ["gathering_storms_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 50,
	},
	{
		"id": "pair_meris_alden_ledger_of_mercy",
		"unit_a": "Sister Meris",
		"unit_b": "Brother Alden",
		"title": "Ledger of Mercy",
		"text": "Meris is re-copying supply requests in a hand so exact it looks punitive. Alden pauses beside her table.\n\n\"You’ve rewritten that list twice,\" he says.\n\"The first version was inefficient. The second was penance disguised as efficiency.\" She does not look up.\nAlden considers that. \"Mercy can be disciplined too, you know. It needn’t always arrive as softness.\"\nThat finally makes her lift her head. \"And what if I no longer trust softness?\"\n\"Then start with fairness,\" he replies. \"It is harder to counterfeit than purity.\"",
		"threshold_a": "trusted",
		"threshold_b": "known",
		"requires_flags": ["greyspire_hub_established"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 45,
	},
	{
		"id": "pair_corvin_sorrel_abyssal_margins",
		"unit_a": "Corvin Ash",
		"unit_b": "Sorrel",
		"title": "Abyssal Margins",
		"text": "Sorrel is comparing copied sigils from the Order ruins when Corvin steps into the lantern glow.\n\n\"You left out the unstable variations,\" he notes.\nSorrel looks up, startled. \"I omitted the ones most likely to kill the reader.\"\n\"Prudent,\" Corvin says. \"And a little paternalistic.\"\nSorrel frowns. \"I dislike corpses in the margins.\"\nCorvin’s smile is thin and almost kind. \"Reasonable. Still, one must know exactly which truths are dangerous before deciding who gets to survive them.\"",
		"threshold_a": "trusted",
		"threshold_b": "trusted",
		"requires_flags": ["echoes_of_the_order_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 55,
	},
	{
		"id": "pair_hadrien_meris_trial_without_fire",
		"unit_a": "Ser Hadrien",
		"unit_b": "Sister Meris",
		"title": "Trial Without Fire",
		"text": "Meris stands rigid before an extinguished brazier as Hadrien’s spectral light flickers at its edge.\n\n\"Your age called judgment holy,\" she says.\n\"So did yours,\" Hadrien replies, not unkindly.\nShe closes her eyes. \"Then perhaps we both served altars too eager for flame.\"\nThe old knight regards her in silence. \"Perhaps. The worth of an oath is not whether it was once spoken proudly. It is whether, after ruin, it can still be turned toward the living.\"\nWhen Meris speaks again, her voice is quieter. \"I am trying.\" \n\"I know,\" Hadrien says.",
		"threshold_a": "bonded",
		"threshold_b": "trusted",
		"requires_flags": ["echoes_of_the_order_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 60,
	},
	{
		"id": "pair_kaelen_sabine_watch_rotations",
		"unit_a": "Kaelen",
		"unit_b": "Sabine Varr",
		"title": "Watch Rotations",
		"text": "Sabine is halfway through revising the sentry rotation when Kaelen stops at her shoulder.\n\n\"You moved the weakest post closer to the kitchens,\" he says.\n\"Yes,\" she replies. \"That route sees traffic. Mistakes are noticed faster there.\"\nHe studies the list, then nods once. \"You plan for failure honestly. Rare trait.\"\nSabine folds her arms. \"I dislike preventable disasters.\"\nKaelen’s mouth twitches. \"Then you’ll fit in well here. Our disasters are rarely preventable, but we make a sport of trying anyway.\"",
		"threshold_a": "trusted",
		"threshold_b": "known",
		"requires_flags": ["gathering_storms_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 45,
	},
		{
		"id": "pair_celia_meris_unlearning",
		"unit_a": "Celia",
		"unit_b": "Sister Meris",
		"title": "Unlearning",
		"text": "Celia is rewrapping the leather around a practice spear when Meris stops beside her, hands folded too tightly.\n\n\"You still correct your posture when no one is watching,\" Meris says.\nCelia does not look up. \"So do you.\"\nThat lands harder than either of them expected.\n\nMeris exhales. \"They taught us obedience as if it were the same thing as virtue.\"\n\"They taught us usefulness as if it were the same thing as love,\" Celia replies.\nFor a long moment, neither speaks.\n\nThen Meris says, quieter, \"Do you ever stop hearing them?\"\nCelia tightens the final knot and finally meets her eyes. \"No. But I have started hearing myself too.\"",
		"threshold_a": "trusted",
		"threshold_b": "trusted",
		"requires_flags": ["market_of_masks_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 55,
	},
	{
		"id": "pair_rufus_sabine_after_counts",
		"unit_a": "Rufus",
		"unit_b": "Sabine Varr",
		"title": "After the Counts",
		"text": "Sabine is finishing a casualty list by lantern-light when Rufus sets a dented mug beside her.\n\n\"You look like you’re trying to win an argument with the paper,\" he says.\n\"The paper is preferable to most command staff,\" Sabine replies.\nHe grunts approval and leans against the crate. \"Still. Numbers after a bad fight are a rotten kind of company.\"\nShe studies him for a moment. \"And what would you prescribe?\"\n\"Tea. Swearing. Maybe sitting near someone who understands the difference between loss and arithmetic.\"\nSabine looks back at the page, then nudges the second stool out with her boot. \"Very well. Sit quietly and be insightful at me.\"",
		"threshold_a": "known",
		"threshold_b": "known",
		"requires_flags": ["greyspire_hub_established"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 45,
	},
	{
		"id": "pair_nyx_darian_bad_rooms",
		"unit_a": "Nyx",
		"unit_b": "Darian",
		"title": "Bad Rooms",
		"text": "Darian is turning a silver coin over his knuckles when Nyx slips into the empty chair opposite him.\n\n\"You’ve got the expression of someone remembering a ballroom and hating it,\" Nyx says.\nDarian smiles without warmth. \"And you’ve got the posture of someone mapping exits before the conversation has started.\"\n\"That is because I respect architecture,\" Nyx replies.\nHe laughs softly, then lets it die. \"You know what the worst rooms have in common?\"\nNyx tilts their head.\n\"Everyone inside them understands exactly what is happening,\" Darian says, \"and keeps smiling anyway.\"\nNyx’s eyes go briefly, unexpectedly kind. \"Yes,\" they say. \"I know.\"",
		"threshold_a": "trusted",
		"threshold_b": "trusted",
		"requires_flags": ["market_of_masks_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 50,
	},
	{
		"id": "pair_mira_yselle_right_memory",
		"unit_a": "Mira Ashdown",
		"unit_b": "Yselle Maris",
		"title": "Right Memory",
		"text": "Yselle hums under her breath as she mends a torn costume ribbon. Mira, nearby, is restringing her bow with careful hands.\n\n\"That song,\" Mira says. \"It makes ruins sound prettier than they were.\"\nYselle stills. \"That was not my intention.\"\n\"I know.\" Mira’s voice softens. \"I just… don’t want people loving what happened to us more than they loved us before it did.\"\nYselle sets the ribbon down. \"Then tell me something true. Not dramatic. Just true.\"\nMira thinks for a moment. \"The south roof leaked every spring. The baker sang badly. The square smelled like apples after rain.\"\nYselle smiles, small and serious. \"Good,\" she says. \"That is where the song should start.\"",
		"threshold_a": "known",
		"threshold_b": "known",
		"requires_flags": ["greyspire_hub_established"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 45,
	},
	{
		"id": "pair_branik_alden_bread_and_weight",
		"unit_a": "Branik",
		"unit_b": "Brother Alden",
		"title": "Bread and Weight",
		"text": "Branik is kneading dough with his usual terrifying competence when Alden steps into the cookfire glow.\n\n\"You work like a man trying to apologize to flour,\" Alden says.\nBranik huffs a laugh. \"Flour’s easier than people. It tells you when you’ve pushed too hard.\"\nAlden leans on the table. \"People do too. Just less honestly.\"\nBranik goes quiet for a moment, then says, \"I spent a long time being useful because I did not know how to be forgiven.\"\nAlden nods as if that is not a shocking confession at all. \"Then it is fortunate this camp keeps needing both bread and practice.\"\nBranik’s smile is tired, but real. \"That may be the kindest sermon I’ve ever heard.\"",
		"threshold_a": "trusted",
		"threshold_b": "known",
		"requires_flags": ["greyspire_hub_established"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 50,
	},
	{
		"id": "pair_maela_pell_height_and_heart",
		"unit_a": "Maela Thorn",
		"unit_b": "Pell Rowan",
		"title": "Height and Heart",
		"text": "Pell nearly drops his practice spear when Maela lands beside him from the wagon roof.\n\n\"Do you always arrive like divine punishment?\" he blurts.\nMaela grins. \"Only for people with especially funny expressions.\"\nHe tries to recover his dignity and fails nobly. \"I was rehearsing.\" \n\"I know,\" she says, gentler now. \"You rehearse courage like it’s a speech.\"\nPell looks down. \"Is that bad?\"\nMaela hooks a thumb toward the dark sky. \"No. It just means you think bravery happens before the fall. Usually it happens during.\" She nudges his shoulder with hers. \"Good news, though. You’re still trying on the way down. That counts for more than style.\"",
		"threshold_a": "known",
		"threshold_b": "known",
		"requires_flags": [],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 40,
	},
	{
		"id": "pair_hadrien_liora_light_without_fear",
		"unit_a": "Ser Hadrien",
		"unit_b": "Liora",
		"title": "Light Without Fear",
		"text": "Liora has finished a quiet prayer when Hadrien’s spectral glow gathers at the edge of the shrine.\n\n\"Your age and mine used some of the same words,\" he says.\nLiora lowers her hands. \"I know. That is part of the trouble.\"\nThe old knight inclines his head. \"And yet you still speak them.\"\n\"Because I am trying to keep the mercy and bury the machinery built around it,\" she replies.\nHadrien is silent for a long moment. \"Then perhaps you are doing what none of us managed in time.\"\nLiora’s eyes shine, but she does not look away. \"I would settle for doing it before more people die of our certainty.\" \n\"A worthy revision,\" Hadrien says softly.",
		"threshold_a": "bonded",
		"threshold_b": "trusted",
		"requires_flags": ["echoes_of_the_order_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 60,
	},
	{
		"id": "pair_tamsin_liora_hands_that_stay",
		"unit_a": "Tamsin Reed",
		"unit_b": "Liora",
		"title": "Hands That Stay",
		"text": "Tamsin is trying and failing to hide the shake in her hands while sorting dried herbs. Liora quietly takes the bowl before it spills.\n\n\"I’m fine,\" Tamsin says too quickly.\n\"You are useful,\" Liora replies. \"That is not the same thing.\"\nTamsin blinks at her.\nLiora sets the bowl down and begins dividing the herbs into neater piles. \"You are allowed to become tired before you become useless. The order we were given on that point was… not merciful.\"\nTamsin lets out a weak, startled laugh. \"That might be the most frighteningly kind thing anyone’s said to me all week.\"\nLiora’s mouth twitches. \"Then sit. Frightening kindness can continue while seated.\"",
		"threshold_a": "known",
		"threshold_b": "trusted",
		"requires_flags": ["greyspire_hub_established"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 45,
	},
	{
		"id": "pair_garrick_sabine_perimeter_of_honor",
		"unit_a": "Garrick Vale",
		"unit_b": "Sabine Varr",
		"title": "Perimeter of Honor",
		"text": "Sabine is checking the night perimeter when Garrick falls into step beside her.\n\n\"You do your own inspections,\" he notes.\n\"I distrust delegated certainty,\" she replies.\nHe gives a low hum of approval. \"Sensibly put. Edranor had too much confidence in uniforms and too little in outcomes.\"\nSabine glances at him. \"You still talk about honor as if it might recover.\"\nGarrick’s answer comes after a pause. \"Not recover. Earn. Again. There is a difference.\"\nFor the rest of the round, they walk in companionable silence, two professionals keeping faith with the parts of duty that still deserve it.",
		"threshold_a": "trusted",
		"threshold_b": "known",
		"requires_flags": ["gathering_storms_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 50,
	},
	{
		"id": "pair_rufus_branik_feeding_the_living",
		"unit_a": "Rufus",
		"unit_b": "Branik",
		"title": "Feeding the Living",
		"text": "Rufus shoulders a sack of grain into the cook area and drops it with a grunt. Branik catches it before it topples.\n\n\"You carry supplies like they insulted your family,\" Branik says.\n\"Most supplies have,\" Rufus replies. \"Usually by not existing when needed.\"\nBranik ties the sack open and checks the grain with careful fingers. \"Still. We’ve got enough tonight.\"\nRufus watches him for a moment. \"That matters more than speeches ever do. A hot meal tells people tomorrow exists.\"\nBranik’s expression softens. \"Then let’s be rude enough to keep proving it.\"",
		"threshold_a": "known",
		"threshold_b": "known",
		"requires_flags": ["greyspire_hub_established"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 45,
	},
	{
		"id": "pair_inez_mira_names_for_ruins",
		"unit_a": "Inez",
		"unit_b": "Mira Ashdown",
		"title": "Names for Ruins",
		"text": "Mira is scraping mud from her boots when Inez approaches with a small bundle of herbs.\n\n\"For smoke-sickness,\" Inez says, offering them.\nMira takes them carefully. \"Thank you.\"\nThey stand in silence for a while, watching the tree line.\n\"People keep trying to name what happened to Oakhaven for me,\" Mira says at last.\nInez’s mouth tightens. \"Outsiders love names. Makes theft feel organized.\"\nMira laughs once, sharp and surprised. \"Yes.\"\nInez nods toward the herbs. \"Then keep your own names for it. The true ones. Land remembers better when the living do too.\"",
		"threshold_a": "trusted",
		"threshold_b": "known",
		"requires_flags": ["greyspire_hub_established"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 45,
	},
	{
		"id": "pair_tariq_corvin_wrong_questions",
		"unit_a": "Tariq",
		"unit_b": "Corvin Ash",
		"title": "Wrong Questions",
		"text": "Tariq finds Corvin near the ward-stakes, staring at nothing visible in a way that feels professionally offensive.\n\n\"You have the posture of a man about to make scholarship everyone else’s problem,\" Tariq says.\nCorvin glances at him. \"Only because everyone else insists on making ignorance communal.\"\nTariq actually smiles at that. \"There you are. I was worried you’d become respectable.\"\nCorvin’s expression shifts by a fraction. \"And I was worried you’d confuse cynicism with caution forever.\"\nTariq folds his arms. \"I do not confuse them. I layer them.\" \n\"Ah,\" Corvin says. \"Then perhaps there is hope for you yet.\"",
		"threshold_a": "trusted",
		"threshold_b": "trusted",
		"requires_flags": ["echoes_of_the_order_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 55,
	},
	{
		"id": "pair_maela_yselle_grace_in_motion",
		"unit_a": "Maela Thorn",
		"unit_b": "Yselle Maris",
		"title": "Grace in Motion",
		"text": "Yselle watches Maela balance along the top of a supply cart as if the wagon were a stage built for one.\n\n\"That is either an entrance or a cry for attention,\" Yselle says.\nMaela beams. \"Why choose?\"\nYselle laughs, then studies her more carefully. \"You move like someone who trusts falling.\"\nMaela hops down, lighter now. \"No. I move like someone who got tired of asking the ground for permission.\"\nYselle’s smile softens into something warmer. \"That,\" she says, \"is a line worth stealing.\"\n\"Take it,\" Maela replies. \"I’ve got more.\"",
		"threshold_a": "known",
		"threshold_b": "known",
		"requires_flags": ["market_of_masks_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 40,
	},
		{
		"id": "pair_darian_yselle_velvet_knives",
		"unit_a": "Darian",
		"unit_b": "Yselle Maris",
		"title": "Velvet Knives",
		"text": "Yselle is unpinning stage ribbons from her sleeves when Darian appears with two cups and the sort of smile that usually means trouble.\n\n\"You handed a room its own reflection tonight,\" he says.\nYselle accepts the cup carefully. \"And you looked offended they recognized themselves.\"\nHe laughs under his breath. \"Only impressed. Most people can’t wound with grace.\"\n\"That sounds perilously like flirting,\" she says.\nDarian’s gaze lingers a fraction too long. \"No,\" he replies softly. \"Flirting is kinder. That was professional admiration.\"\nYselle looks down into the steam so he cannot quite see her smile. \"Dangerous distinction,\" she murmurs.",
		"threshold_a": "trusted",
		"threshold_b": "trusted",
		"requires_flags": ["market_of_masks_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 50,
	},
	{
		"id": "pair_maela_mira_roofline_breath",
		"unit_a": "Maela Thorn",
		"unit_b": "Mira Ashdown",
		"title": "Roofline Breath",
		"text": "Mira climbs onto the wagon roof expecting solitude and finds Maela already there, knees drawn up, watching the stars like they owe her gossip.\n\n\"You too?\" Maela asks.\n\"It’s quieter up here,\" Mira says.\n\"That’s because fear has to work harder when it wants to follow you onto a roof.\"\nMira snorts despite herself. For a while they sit in companionable silence.\nThen Maela says, very gently, \"You don’t always have to remember from the ground.\"\nMira’s throat tightens. \"No?\"\n\"No.\" Maela tips her face toward the sky. \"Sometimes it helps to remember from somewhere the fire never reached.\"",
		"threshold_a": "known",
		"threshold_b": "trusted",
		"requires_flags": ["greyspire_hub_established"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 45,
	},
	{
		"id": "pair_nyx_liora_bandage_and_blade",
		"unit_a": "Nyx",
		"unit_b": "Liora",
		"title": "Bandage and Blade",
		"text": "Nyx is trying to rewrap a cut on their forearm with one hand when Liora quietly takes the bandage away.\n\n\"I had it,\" Nyx mutters.\n\"You had blood on your cuff and stubbornness in your jaw,\" Liora replies. \"Those are not the same thing.\"\nNyx watches her work. \"You always sound like mercy is an order someone forgot to issue.\"\nLiora ties the knot carefully. \"And you always sound like pain is a tax you’ve already budgeted for.\"\nNyx’s expression flickers into something small and unguarded. \"Occupational hazard.\"\nLiora meets their eyes. \"Then let it be a shared one, for five minutes.\"",
		"threshold_a": "trusted",
		"threshold_b": "trusted",
		"requires_flags": [],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 45,
	},
	{
		"id": "pair_hest_tamsin_smoke_and_salves",
		"unit_a": "Hest \"Sparks\"",
		"unit_b": "Tamsin Reed",
		"title": "Smoke and Salves",
		"text": "Tamsin is cataloguing salves when Hest bursts into the tent smelling faintly of smoke and triumph.\n\n\"Good news,\" Hest says. \"Nothing exploded in a medically significant way.\"\nTamsin closes her eyes. \"That sentence contains too much uncertainty.\"\nHest sets down a bent metal bracket. \"I came for balm. And maybe reassurance. In that order.\"\nTamsin reaches for the salve with a sigh that is mostly fondness now. \"Sit. If you drip molten nonsense on my floor again, I’ll start charging you by the panic.\"\nHest beams. \"That is the nicest threat anyone’s made all day.\"",
		"threshold_a": "known",
		"threshold_b": "known",
		"requires_flags": ["greyspire_hub_established"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 40,
	},
	{
		"id": "pair_pell_tamsin_keep_breathing",
		"unit_a": "Pell Rowan",
		"unit_b": "Tamsin Reed",
		"title": "Keep Breathing",
		"text": "Pell is reciting a training mantra under his breath when Tamsin passes with a tray of poultices.\n\n\"You sound like you’re trying to negotiate with your lungs,\" she says.\nHe flushes. \"It helps. Before drills. Before battle. Before… everything, really.\"\nTamsin shifts the tray to one arm. \"Then maybe stop asking your breathing to win the war for you. Let it just be breathing.\"\nHe stares at her. \"Can it do that?\"\nFor the first time all day, Tamsin smiles without apology. \"Yes. That’s the wonderful part. Some things are allowed to help without being heroic.\"",
		"threshold_a": "known",
		"threshold_b": "known",
		"requires_flags": [],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 40,
	},
	{
		"id": "pair_kaelen_meris_names_for_guilt",
		"unit_a": "Kaelen",
		"unit_b": "Sister Meris",
		"title": "Names for Guilt",
		"text": "Meris is burning old scrap orders one strip at a time when Kaelen pauses beside the brazier.\n\n\"Ceremonial?\" he asks.\n\"Cowardly,\" she answers. \"I do not know the proper distinction anymore.\"\nHe watches the ash fold in on itself. \"There are many names for guilt. Duty. Penance. Tradition. Necessity.\"\nMeris lets out a brittle laugh. \"You say that like a man who has tried them all.\"\nKaelen’s expression doesn’t change, which is answer enough. After a moment he adds, \"The trick is finding one that doesn’t ask someone else to carry it for you.\"\nMeris feeds another strip to the fire. \"I suspected you would say something unbearable and useful.\"",
		"threshold_a": "close",
		"threshold_b": "trusted",
		"requires_flags": ["dawnkeep_siege_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 55,
	},
	{
		"id": "pair_corvin_hadrien_dust_of_saints",
		"unit_a": "Corvin Ash",
		"unit_b": "Ser Hadrien",
		"title": "Dust of Saints",
		"text": "Corvin stands within the old chapel ruins, studying stone that remembers too much. Hadrien’s ghost-light gathers beside a weathered arch.\n\n\"You built monuments to certainty,\" Corvin says, not looking at him.\n\"We built shelters for fear,\" Hadrien replies. \"Then mistook the shelter for the truth.\"\nCorvin turns at that, surprised into honesty. \"That may be the most intelligent thing any dead knight has ever said to me.\"\nHadrien’s mouth curves faintly. \"A low bar, I suspect.\"\nCorvin looks back at the broken altar. \"Do you ever wish the Order had simply vanished cleanly?\"\n\"No,\" Hadrien says. \"Clean endings teach the living nothing. Ruins are harder. Better.\"",
		"threshold_a": "bonded",
		"threshold_b": "trusted",
		"requires_flags": ["echoes_of_the_order_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 60,
	},
	{
		"id": "pair_sabine_meris_cold_mercy",
		"unit_a": "Sabine Varr",
		"unit_b": "Sister Meris",
		"title": "Cold Mercy",
		"text": "Sabine is reviewing prisoner supply requests when Meris stops at her table.\n\n\"You approved the blankets,\" Meris says.\n\"Of course I did,\" Sabine replies. \"Cold does not improve truth. It only cheapens the people using it.\"\nMeris studies her for a long moment. \"You say mercy like a logistical principle.\"\nSabine finally looks up. \"And you say it like a relic.\"\nFor a breath, the air between them is sharp.\nThen Meris nods once. \"Perhaps it has been both for too long.\"\nSabine slides the ledger toward her. \"Then let us try administration instead of sanctimony and see if the world notices.\"",
		"threshold_a": "trusted",
		"threshold_b": "trusted",
		"requires_flags": ["gathering_storms_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 50,
	},
	{
		"id": "pair_rufus_veska_after_impact",
		"unit_a": "Rufus",
		"unit_b": "Veska Moor",
		"title": "After Impact",
		"text": "Rufus is hammering a bent plate back into shape when Veska sets her shield beside the anvil.\n\n\"Yours too?\" he asks.\n\"Mine always,\" she says.\nHe runs a thumb over a deep dent. \"Funny thing. People think holding the line looks noble. From back here it mostly looks expensive.\"\nVeska’s laugh is low and tired. \"And repetitive.\"\nHe nods. \"Still did it.\"\nShe rests a hand on the shield’s rim. \"Still will.\"\nRufus gives the metal one last strike and hands it back. \"Good. I’d hate to repair something that didn’t intend to survive me doing it.\"",
		"threshold_a": "trusted",
		"threshold_b": "trusted",
		"requires_flags": ["dawnkeep_siege_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 50,
	},
	{
		"id": "pair_yselle_pell_courage_without_audience",
		"unit_a": "Yselle Maris",
		"unit_b": "Pell Rowan",
		"title": "Courage Without an Audience",
		"text": "Pell is practicing introductions under his breath when Yselle catches the end of one and nearly laughs.\n\n\"Please tell me that was meant for a duke,\" she says.\nPell goes scarlet. \"I was trying to sound… composed.\"\nYselle softens immediately. \"Forgive me. It was earnest, not foolish. Those are different things.\"\nHe rubs the back of his neck. \"I keep wanting bravery to sound better than it feels.\"\nYselle steps closer, voice warm now. \"Most real courage happens offstage, Pell. No applause. No lighting. Just a person deciding not to turn away.\" \nHe nods slowly. \"That sounds harder.\"\n\"It is,\" she says. \"That’s why it matters.\"",
		"threshold_a": "known",
		"threshold_b": "known",
		"requires_flags": [],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 40,
	},
	{
		"id": "pair_nyx_maela_not_falling",
		"unit_a": "Nyx",
		"unit_b": "Maela Thorn",
		"title": "Not Falling",
		"text": "Maela is balanced on the camp palisade like gravity is a rumor when Nyx appears below, unimpressed.\n\n\"One day,\" Nyx says, \"you are going to do that in front of someone who mistakes panic for care.\"\nMaela grins down at them. \"You say that like you’d be worried.\"\nNyx crosses their arms. \"I say that like I dislike paperwork caused by preventable idiocy.\"\nMaela hops down lightly, still smiling. \"That’s practically affection in your dialect.\"\nNyx’s expression betrays them for half a second. \"Don’t get greedy,\" they mutter.\nMaela laughs, bright and warm. \"Too late.\"",
		"threshold_a": "trusted",
		"threshold_b": "known",
		"requires_flags": ["greyspire_hub_established"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 45,
	},
	{
		"id": "pair_liora_meris_revised_prayer",
		"unit_a": "Liora",
		"unit_b": "Sister Meris",
		"title": "Revised Prayer",
		"text": "Liora is copying a litany into a fresh notebook when Meris pauses behind her.\n\n\"You changed the wording,\" Meris says.\n\"Yes,\" Liora replies. \"The old line asked for obedience before mercy. I thought I’d try the reverse.\"\nMeris stares at the page as if it has insulted a century of architecture. \"You can do that?\"\nLiora looks up, almost smiling. \"We changed far crueler things and still called them doctrine. I refuse to believe kindness is the one part too sacred to edit.\"\nSomething in Meris’s face tightens, then softens. \"May I see?\"\nLiora turns the notebook toward her without hesitation. \"Please.\"",
		"threshold_a": "trusted",
		"threshold_b": "trusted",
		"requires_flags": ["echoes_of_the_order_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 55,
	},
		{
		"id": "pair_kaelen_nyx_after_dawnkeep_truth",
		"unit_a": "Kaelen",
		"unit_b": "Nyx",
		"title": "After the Truth",
		"text": "Nyx finds Kaelen sitting awake long after the fires have burned low, one hand braced against the wagon wheel as if the earth might tilt without warning.\n\n\"You look awful,\" Nyx says.\n\"Your bedside manner remains inspiring,\" Kaelen replies.\nThey crouch across from him, all sarcasm stripped down to something leaner. \"You don’t have to earn the right to collapse after this.\"\nHe lets out a breath that sounds older than the night. \"It is difficult to tell the difference between resting and letting everyone down.\"\nNyx’s jaw tightens. \"Then borrow mine. I’m excellent at deciding who gets to fall apart and who gets left alone about it.\"\nKaelen looks at them, really looks, and the ghost of a smile finally reaches his face. \"That is an alarming offer.\"\n\"Yes,\" Nyx says softly. \"Take it anyway.\"",
		"threshold_a": "close",
		"threshold_b": "trusted",
		"requires_flags": ["dawnkeep_siege_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 60,
	},
	{
		"id": "pair_kaelen_liora_after_order_ruins",
		"unit_a": "Kaelen",
		"unit_b": "Liora",
		"title": "What We Keep",
		"text": "Liora is folding a torn altar cloth into something smaller and more useful when Kaelen stops beside her.\n\n\"You’re repurposing relics,\" he says.\n\"I’m refusing to let them keep pretending they were innocent,\" Liora answers.\nHe is quiet for a long moment. \"I used to think preserving the Order meant preserving its shape.\"\nShe smooths the cloth once with both palms. \"And now?\"\nKaelen looks toward the ruined chapel. \"Now I think if anything holy survived us, it was never the stone.\" \nLiora’s eyes shine with exhausted relief. \"Good,\" she says. \"Because I do not know how to save walls anymore. Only people.\"\nHis voice softens. \"That was always the better liturgy.\"",
		"threshold_a": "bonded",
		"threshold_b": "trusted",
		"requires_flags": ["echoes_of_the_order_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 60,
	},
	{
		"id": "pair_meris_alden_after_ledger",
		"unit_a": "Sister Meris",
		"unit_b": "Brother Alden",
		"title": "The Names That Remain",
		"text": "Meris is staring at a copied list of the dead as if it might pass sentence first. Alden sits beside her without asking permission.\n\n\"I used to believe records were a kind of mercy,\" she says at last. \"Order against oblivion.\"\nAlden nods. \"Sometimes they are.\"\nHer hand tightens around the page. \"And sometimes they are just cleaner ways to keep count of what we allowed.\"\nHe does not rush to contradict her. That, more than anything, breaks her composure.\n\"I can still remember the sound of my own voice saying yes,\" she whispers.\nAlden reaches over, not to take the list away, but to steady the hand holding it. \"Then let memory do what punishment never can,\" he says quietly. \"Let it make you gentler than the person who signed.\" \nMeris closes her eyes. \"I am trying.\"\n\"I know,\" he says. \"That is why I sat down.\"",
		"threshold_a": "bonded",
		"threshold_b": "trusted",
		"requires_flags": ["gathering_storms_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 60,
	},
	{
		"id": "pair_corvin_meris_no_clean_hands",
		"unit_a": "Corvin Ash",
		"unit_b": "Sister Meris",
		"title": "No Clean Hands",
		"text": "Corvin finds Meris washing her hands in a basin that has long since gone cold.\n\n\"You’ll take the skin off at that rate,\" he observes.\n\"It would hardly be the first useful thing pain accomplished,\" she replies.\nHe leans against the tent post, expression unreadable. \"A disappointing theory. Pain is efficient, yes. Useful? Rarely.\"\nMeris does not look up. \"You speak like a man untroubled by consequence.\"\n\"No,\" Corvin says, softer than she expected. \"I speak like a man who has learned that guilt is not purification. It is only weight.\"\nThat finally makes her still.\n\"Then what is left?\" she asks.\nCorvin watches the water tremble around her hands. \"Choice,\" he says. \"Repeated until it begins to resemble a soul again.\"",
		"threshold_a": "bonded",
		"threshold_b": "bonded",
		"requires_flags": ["echoes_of_the_order_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 65,
	},
	{
		"id": "pair_hadrien_kaelen_last_standard",
		"unit_a": "Ser Hadrien",
		"unit_b": "Kaelen",
		"title": "The Last Standard",
		"text": "Kaelen has laid an old Dawn banner across a crate, patching a tear no one will ever inspect at parade distance. Hadrien’s spectral form flickers beside him.\n\n\"You still tend our dead cloth,\" the old knight says.\n\"Not yours,\" Kaelen replies. \"Mine. I carried enough of it into the world to owe the work personally.\"\nHadrien studies him with the weary patience of a ghost who has had too much time to regret admiration. \"We taught you to bear symbols before you were ready to question them.\"\nKaelen’s hands stop. \"You taught me how to stand up.\"\n\"And not enough about when to kneel,\" Hadrien says.\nThe silence that follows is full of old ruin.\nThen Kaelen asks, almost like a son who should not still need the answer, \"Was any of it worthy?\"\nHadrien’s voice is very quiet. \"You were. And perhaps, because you survived us badly enough to tell the truth, something of the oath may yet be.\"",
		"threshold_a": "bonded",
		"threshold_b": "bonded",
		"requires_flags": ["echoes_of_the_order_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 70,
	},
	{
		"id": "pair_sabine_rufus_the_people_after",
		"unit_a": "Sabine Varr",
		"unit_b": "Rufus",
		"title": "The People After",
		"text": "Rufus is repairing a ration cart wheel when Sabine arrives with a ledger tucked under one arm.\n\n\"We can provision for the siege,\" she says. \"The harder question is after.\"\nHe keeps working. \"After is when policy gets shy about bodies.\"\nSabine exhales, almost a laugh. \"That may be the most concise strategic doctrine I have heard in years.\"\nHe glances up at her. \"I’m serious. Everyone plans for the battle. No one likes planning for the people who remain standing in the mud afterward asking what victory is supposed to taste like.\"\nShe looks down at the ledger in her hands, then closes it. \"Then let us be unpopular and plan for them anyway.\"\nRufus nods once. \"Good. That’s usually where the decent work starts.\"",
		"threshold_a": "trusted",
		"threshold_b": "trusted",
		"requires_flags": ["gathering_storms_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 55,
	},
	{
		"id": "pair_mira_branik_when_home_is_smell",
		"unit_a": "Mira Ashdown",
		"unit_b": "Branik",
		"title": "When Home Is a Smell",
		"text": "Branik is pulling bread from the firestone when Mira stops short, breath catching before she can hide it.\n\n\"Sorry,\" she says quickly. \"It just—\"\n\"Smells familiar,\" Branik finishes gently.\nShe nods, staring too hard at the loaf. \"I hate that something so ordinary can hurt this much.\"\nBranik sets the bread down between them and tears off the heel. \"That’s because ordinary things do most of the holding. Roof beams. Soup. Someone humming in the next room. When they’re gone, the world notices badly.\"\nMira takes the piece he offers, fingers trembling only a little. \"Do you ever stop missing it?\"\nBranik’s smile is warm and ruined around the edges. \"No. But sometimes you get good enough at feeding the living that missing home starts sounding less like an ending and more like a promise.\"",
		"threshold_a": "trusted",
		"threshold_b": "trusted",
		"requires_flags": ["greyspire_hub_established"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 50,
	},
	{
		"id": "pair_inez_garrick_after_borders_fail",
		"unit_a": "Inez",
		"unit_b": "Garrick Vale",
		"title": "After Borders Fail",
		"text": "Inez is resetting snare bells along the perimeter when Garrick joins her with a map he no longer trusts.\n\n\"This line means nothing now,\" he says, staring at the ink.\nInez does not take the map. \"It meant something to someone. That is why it hurt people.\"\nHe folds it once, sharply. \"I was taught to honor borders.\"\n\"And I was taught to notice who bled when they moved,\" she replies.\nThat silences him.\nAfter a while, she points into the dark. \"There. Water. Windbreak. Good ground to keep people through the night.\"\nGarrick looks where she points, then folds the map smaller and puts it away. \"You always answer with land.\"\nInez’s voice is quiet. \"Land does not lie about what it can hold.\"",
		"threshold_a": "bonded",
		"threshold_b": "trusted",
		"requires_flags": ["gathering_storms_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 55,
	},
	{
		"id": "pair_tariq_sorrel_after_the_archive_opens",
		"unit_a": "Tariq",
		"unit_b": "Sorrel",
		"title": "After the Archive Opens",
		"text": "Sorrel is copying notes so quickly their ink keeps outrunning their hand. Tariq watches for a moment, then quietly moves the lamp closer.\n\n\"You are about to discover whether obsession can be diagnosed by penmanship,\" he says.\nSorrel startles, then blinks at the adjusted light. \"Thank you.\"\nHe waves that off. \"Do not make it sentimental. I only need you able to read your own catastrophe tomorrow.\"\nSorrel smiles despite their exhaustion. \"That was almost kind.\"\nTariq leans against the table, gaze softening in spite of himself. \"Knowledge this dangerous is easiest to survive when someone else in the room knows exactly why you are shaking.\"\nSorrel’s pen slows. \"You do.\"\n\"Unfortunately,\" Tariq says. \"Yes.\"",
		"threshold_a": "bonded",
		"threshold_b": "bonded",
		"requires_flags": ["echoes_of_the_order_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 55,
	},
	{
		"id": "pair_celia_liora_after_verdict",
		"unit_a": "Celia",
		"unit_b": "Liora",
		"title": "After the Verdict",
		"text": "Celia stands in full harness though the camp has long since gone to rest. Liora approaches carrying two cups of tea and the sort of determination that has learned to look gentle on purpose.\n\n\"You are doing penance again,\" Liora says.\nCelia stiffens. \"I am standing watch.\"\n\"On no assigned post. In polished armor. Alone.\"\nThat almost makes Celia laugh. Almost.\nLiora offers her a cup. \"You do not have to become a monument every time the world reminds you what it once demanded of you.\"\nCelia takes the tea with both hands, as if it requires courage. \"And if standing still is the only thing keeping me from becoming that girl again?\"\nLiora’s answer comes steady and warm. \"Then let someone stand with you until it isn’t.\"",
		"threshold_a": "bonded",
		"threshold_b": "trusted",
		"requires_flags": ["dawnkeep_siege_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 60,
	},
	{
		"id": "pair_yselle_maela_before_the_last_performance",
		"unit_a": "Yselle Maris",
		"unit_b": "Maela Thorn",
		"title": "Before the Last Performance",
		"text": "Yselle is pinning a ribbon into place with hands steadier than her breathing. Maela drops onto the crate beside her and immediately pretends not to notice.\n\n\"You do know this isn’t a stage,\" Maela says lightly.\n\"Everything with witnesses is a stage,\" Yselle replies.\nMaela turns that over, then bumps her shoulder gently against hers. \"And if tonight there are no witnesses?\"\nYselle’s smile turns fragile in a way she would hate being seen. \"Then perhaps I would not know where to put my hands.\"\nMaela takes one of them and holds it between both of hers without ceremony. \"Here,\" she says.\nFor once, Yselle does not answer with charm. She only squeezes back.",
		"threshold_a": "trusted",
		"threshold_b": "trusted",
		"requires_flags": ["gathering_storms_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 55,
	},
	{
		"id": "pair_nyx_maela_if_we_live",
		"unit_a": "Nyx",
		"unit_b": "Maela Thorn",
		"title": "If We Live",
		"text": "Maela is lying on her back atop the supply wagon, staring at the sky like it might offer useful gossip. Nyx appears below and tosses a pebble up at her.\n\n\"Elegant,\" Maela says.\n\"You were ignoring reality from a height again,\" Nyx replies.\nShe props herself up on one elbow. \"And you came all the way over here to object? That is almost tender.\"\nNyx folds their arms, expression guarded and exhausted all at once. \"If tomorrow goes badly, I would prefer not to discover I left things unsaid out of spite.\"\nThat wipes the grin from Maela’s face.\n\"Then say one,\" she says softly.\nNyx looks away first. \"If we live,\" they mutter, \"you are not allowed to vanish without warning.\"\nMaela’s answer is gentler than the night deserves. \"If we live, I’ll make you ask properly.\"",
		"threshold_a": "bonded",
		"threshold_b": "trusted",
		"requires_flags": ["gathering_storms_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 60,
	},
		{
		"id": "pair_darian_yselle_when_the_room_is_empty",
		"unit_a": "Darian",
		"unit_b": "Yselle Maris",
		"title": "When the Room Is Empty",
		"text": "The camp has gone quiet enough for the lanterns to sound loud. Yselle is removing the last of her stage paint when Darian pauses in the entrance, as if stepping any farther in would mean admitting something.\n\n\"You missed your cue,\" she says softly.\n\"I was waiting for the audience to leave,\" he replies.\nThat earns a small smile. \"And now?\"\nDarian studies her without wit for once. \"Now the room is honest. Dangerous change.\"\nYselle sets the cloth down. \"You only like rooms when they lie for you?\"\n\"No,\" he says, voice lower than usual. \"Only when I know what they will cost.\"\nShe steps closer, not enough to touch. \"And this one?\"\nHis smile is tired and real all at once. \"Ruination,\" he says. \"Probably.\" \nYselle’s answering look is warm enough to make the word sound survivable.",
		"threshold_a": "bonded",
		"threshold_b": "trusted",
		"requires_flags": ["gathering_storms_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 60,
	},
	{
		"id": "pair_nyx_maela_stay_visible",
		"unit_a": "Nyx",
		"unit_b": "Maela Thorn",
		"title": "Stay Visible",
		"text": "Maela is perched on the palisade again, impossible and bright against the dark. Nyx stops below her and does not bother pretending they were heading somewhere else.\n\n\"You do know there are easier ways to give me grey hairs,\" they mutter.\nMaela grins down at them. \"I didn’t know you were planning on keeping me long enough for that to matter.\"\nNyx opens their mouth, closes it, then looks away toward the tree line. \"That’s not fair.\"\nMaela drops lightly to the ground, all teasing gone now. \"No,\" she says. \"It isn’t.\"\nFor a moment they stand almost shoulder to shoulder.\n\"I’m bad at this part,\" Nyx admits.\n\"Which part?\"\nThey swallow. \"The part where I want someone to stay visible.\"\nMaela’s answer is quiet and immediate. \"Then keep looking at me.\"",
		"threshold_a": "bonded",
		"threshold_b": "trusted",
		"requires_flags": ["gathering_storms_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 60,
	},
	{
		"id": "pair_kaelen_liora_held_together",
		"unit_a": "Kaelen",
		"unit_b": "Liora",
		"title": "Held Together",
		"text": "Liora finds Kaelen re-binding an old leather grip that no longer strictly needs saving. She sits beside him without asking.\n\n\"You repair things when you cannot sleep,\" she says.\n\"I have been caught,\" he replies.\n\"Mm.\" She folds her hands in her lap. \"I pray when I cannot sleep. Which is really just repairing my thoughts with different tools.\"\nThat brings the faintest curve to his mouth.\n\"And does it work?\" he asks.\nLiora considers the question honestly. \"Sometimes. Usually it just keeps me from breaking in one clean direction.\"\nKaelen’s hands still on the leather. After a long silence, he says, \"There are worse ways to be held together.\"\nWhen she leans her shoulder lightly against his, he does not move away.",
		"threshold_a": "bonded",
		"threshold_b": "bonded",
		"requires_flags": ["echoes_of_the_order_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 65,
	},
	{
		"id": "pair_celia_veska_resting_weight",
		"unit_a": "Celia",
		"unit_b": "Veska Moor",
		"title": "Resting Weight",
		"text": "Celia is trying to remove her armor one buckle at a time without acknowledging how tired she is. Veska appears, takes one of the straps in hand, and waits.\n\n\"I can manage,\" Celia says automatically.\n\"I know,\" Veska replies. \"That was not the question.\"\nSomething in Celia’s face shifts, small and painful.\nVeska loosens the strap with calm, practiced hands. \"You do not always have to be the shape the war asked for.\"\nCelia’s voice is barely above a whisper. \"I don’t know who I am when I set it down.\"\nVeska’s answer comes warm and certain. \"Then set down one piece at a time. I’ll stay until the answer starts to look like you.\" \nFor once, Celia lets someone else carry part of the weight.",
		"threshold_a": "bonded",
		"threshold_b": "trusted",
		"requires_flags": ["dawnkeep_siege_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 60,
	},
	{
		"id": "pair_tamsin_liora_gentle_hands",
		"unit_a": "Tamsin Reed",
		"unit_b": "Liora",
		"title": "Gentle Hands",
		"text": "Tamsin is trying to thread a needle through trembling fingers when Liora reaches out and steadies her wrist.\n\n\"Sorry,\" Tamsin says immediately. \"I know. I should rest. I just—\"\n\"You do not have to apologize before I have even been kind to you,\" Liora says, and the softness of it nearly undoes her.\nTamsin laughs once, breathless and embarrassed. \"That sounds made up.\"\nLiora smiles, small and tired. \"Most mercy does, the first time you hear it plainly.\"\nThe needle finally slips through. Tamsin watches their hands for a moment longer than necessary.\n\"You make it look easy,\" she murmurs.\nLiora’s thumb brushes lightly over her knuckles before she lets go. \"No,\" she says. \"I just think it is worth doing carefully.\"",
		"threshold_a": "trusted",
		"threshold_b": "bonded",
		"requires_flags": ["greyspire_hub_established"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 55,
	},
	{
		"id": "pair_tariq_sorrel_shared_lamplight",
		"unit_a": "Tariq",
		"unit_b": "Sorrel",
		"title": "Shared Lamplight",
		"text": "Sorrel has fallen asleep over a page of copied notes, cheek pillowed on their forearm. Tariq notices first, pretends he did not, then quietly moves the lamp so the heat won’t singe the paper.\n\nSorrel wakes just enough to notice him. \"You didn’t leave,\" they murmur.\nTariq keeps his eyes on the annotations. \"I considered it. Then I decided someone ought to be here in case your scholarship attempted self-immolation.\"\nEven half-asleep, Sorrel smiles. \"That was almost sweet.\"\n\"Do not spread that rumor.\" He pauses, then adds more quietly, \"You think more gently than the world deserves. Someone should keep an eye on the edges while you do it.\"\nSorrel blinks up at him through exhaustion and candlelight. \"You already are,\" they say.\nHe does not deny it.",
		"threshold_a": "bonded",
		"threshold_b": "bonded",
		"requires_flags": ["echoes_of_the_order_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 55,
	},
	{
		"id": "pair_garrick_sabine_the_quiet_yes",
		"unit_a": "Garrick Vale",
		"unit_b": "Sabine Varr",
		"title": "The Quiet Yes",
		"text": "Sabine is still working when Garrick returns from the perimeter and sets a folded cloak over the back of her chair.\n\n\"You’ll chill,\" he says.\nShe glances at the cloak, then at him. \"That was almost tender of you.\"\nGarrick’s mouth twitches. \"Careful. I have a reputation for stern dignity to maintain.\"\nSabine finally leans back, letting the fabric settle around her shoulders. \"And if I said I found that reputation less persuasive than the man carrying it?\"\nFor perhaps the first time in recorded history, Garrick Vale has no immediate answer.\nHe steps closer instead, one gloved hand resting on the chair between them.\n\"Then,\" he says at last, voice low and terribly controlled, \"I would ask whether that was meant kindly.\"\nSabine’s expression softens into something rare. \"Yes,\" she says. \"Quietly. But yes.\"",
		"threshold_a": "bonded",
		"threshold_b": "trusted",
		"requires_flags": ["gathering_storms_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 60,
	},
	{
		"id": "pair_mira_maela_when_the_air_is_safe",
		"unit_a": "Mira Ashdown",
		"unit_b": "Maela Thorn",
		"title": "When the Air Is Safe",
		"text": "Maela coaxes Mira onto the highest intact watchpoint in camp with the solemn promise that no one else will bother them there.\n\n\"You keep doing this,\" Mira says, looking out over the dark. \"Taking me somewhere the ground can’t follow.\"\nMaela shrugs, trying for casual and missing by a mile. \"You breathe better up high.\"\nMira is quiet for a long time. Then: \"I think I breathe better when I know you’ll still be there when I look sideways.\"\nThat knocks all the easy grin out of Maela.\n\"I can do that,\" she says, suddenly, fiercely serious. \"I’m very good at inconvenient persistence.\"\nMira laughs, small and shaken and fond. When their shoulders touch, neither of them pretends it was accidental.",
		"threshold_a": "bonded",
		"threshold_b": "trusted",
		"requires_flags": ["gathering_storms_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 60,
	},
	{
		"id": "pair_yselle_maela_hold_still",
		"unit_a": "Yselle Maris",
		"unit_b": "Maela Thorn",
		"title": "Hold Still",
		"text": "Yselle is trying to pin a tear in her sleeve one-handed when Maela reaches over and catches the fabric before she can jab herself.\n\n\"You are impossible to assist gracefully,\" Yselle says.\n\"I contain multitudes,\" Maela replies, grinning. Then, softer: \"Hold still.\"\nYselle does. That may be the more surprising miracle.\nMaela’s fingers are deft in a completely different way than they are on rooftops or rigging. She smooths the seam flat with absent care.\n\"There,\" she says. \"No one will notice.\"\nYselle’s gaze lingers on her face, not the mended cloth. \"That was not really the part I was worried about.\"\nMaela looks up too fast, and suddenly the space between them feels deliberate.\n\"No?\"\nYselle smiles, warm and dangerous in equal measure. \"No.\"",
		"threshold_a": "trusted",
		"threshold_b": "trusted",
		"requires_flags": ["market_of_masks_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 55,
	},
	{
		"id": "pair_nyx_darian_if_i_stay",
		"unit_a": "Nyx",
		"unit_b": "Darian",
		"title": "If I Stay",
		"text": "Darian finds Nyx alone near the supply wagons, knife in hand, cutting old cord down to useful lengths.\n\n\"You always look busiest when you’re about to leave emotionally,\" he says.\nNyx doesn’t glance up. \"And you always sound unbearable when you’re right.\"\nHe crouches beside them anyway. For once, he doesn’t fill the silence with charm.\nAfter a while, Nyx says, \"I was never built for staying.\"\nDarian’s answer is unexpectedly gentle. \"Neither was I. That has stopped neither of us from becoming someone’s problem on purpose.\"\nThat wins a laugh out of them, unwilling and real.\nNyx looks at him then, something rawer than sarcasm in their face. \"And if I stay badly?\"\nDarian’s smile is tired, fond, and far too honest. \"Then I shall simply have to admire you persistently until it improves.\"",
		"threshold_a": "bonded",
		"threshold_b": "trusted",
		"requires_flags": ["gathering_storms_cleared"],
		"forbidden_flags": [],
		"one_time": true,
		"type": "camp_pair",
		"priority": 60,
	},
]

static func get_scenes() -> Array:
	return PAIR_SCENES
