# CampPairSceneTriggerDB.gd
# Phase-1 data for player-triggered pair scenes: two units near each other, player presses E to listen.
# Supports optional memory fields (min_familiarity, once_ever, grants_familiarity, grants_tension).

class_name CampPairSceneTriggerDB

const PAIR_LISTEN_RADIUS_DEFAULT: float = 100.0

const TRIGGER_SCENES: Array = [
	{
		"id": "kaelen_celia_watch_scene",
		"preferred_visit_themes": ["training", "hopeful"],
		"priority": 40,
		"when": { "time_block": "dawn" },
		"unit_a": "Kaelen",
		"unit_b": "Celia",
		"min_familiarity": 0,
		"grants_familiarity": 1,
		"grants_tension": 0,
		"once_ever": true,
		"zone_type": "watch_post",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Kaelen", "text": "You're early." },
			{ "speaker": "Celia", "text": "You're later than I am." },
			{ "speaker": "Kaelen", "text": "Good. Keep that habit." },
			{ "speaker": "Celia", "text": "You make it sound like I need permission." },
		],
	},
	{
		"id": "sorrel_tariq_map_scene",
		"preferred_visit_themes": ["gossip", "normal"],
		"priority": 40,
		"when": { "time_block": "day" },
		"unit_a": "Sorrel",
		"unit_b": "Tariq",
		"min_familiarity": 0,
		"grants_familiarity": 1,
		"grants_tension": 0,
		"once_ever": true,
		"zone_type": "map_table",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Sorrel", "text": "These roads still refuse to match the old charts." },
			{ "speaker": "Tariq", "text": "The roads are not at fault. The charts are." },
			{ "speaker": "Sorrel", "text": "An inspiring defense of bad ink." },
			{ "speaker": "Tariq", "text": "Accuracy and inspiration have never been close cousins." },
		],
	},
	{
		"id": "branik_darian_fire_scene",
		"priority": 40,
		"when": { "time_block": "night" },
		"unit_a": "Branik",
		"unit_b": "Darian",
		"zone_type": "fire",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Branik", "text": "If you sing, sing after the stew." },
			{ "speaker": "Darian", "text": "You wound me. I improve digestion." },
			{ "speaker": "Branik", "text": "You test patience." },
			{ "speaker": "Darian", "text": "And yet you keep feeding me." },
		],
	},
	{
		"id": "liora_alden_infirmary_scene",
		"preferred_visit_themes": ["recovery", "somber"],
		"priority": 38,
		"when": { "time_block": "day" },
		"unit_a": "Liora",
		"unit_b": "Brother Alden",
		"zone_type": "infirmary",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Liora", "text": "They'll mend. You don't have to watch every bandage." },
			{ "speaker": "Brother Alden", "text": "Neither do you. Yet here we are." },
			{ "speaker": "Liora", "text": "Duty looks different when it's quiet." },
			{ "speaker": "Brother Alden", "text": "So does care. Rest when you can." },
		],
	},
	{
		"id": "nyx_hest_workbench_scene",
		"preferred_visit_themes": ["training", "gossip"],
		"priority": 39,
		"when": { "time_block": "day" },
		"unit_a": "Nyx",
		"unit_b": "Hest \"Sparks\"",
		"zone_type": "workbench",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Nyx", "text": "Tell me this contraption only explodes on purpose." },
			{ "speaker": "Hest \"Sparks\"", "text": "It only explodes where I point it. Usually." },
			{ "speaker": "Nyx", "text": "That is not the comfort you think it is." },
			{ "speaker": "Hest \"Sparks\"", "text": "Relax. If something goes wrong, you'll see it coming first." },
			{ "speaker": "Nyx", "text": "I always do. That's the problem." },
		],
	},
	{
		"id": "tamsin_branik_fire_scene",
		"priority": 38,
		"when": { "time_block": "night" },
		"unit_a": "Tamsin Reed",
		"unit_b": "Branik",
		"min_familiarity": 0,
		"grants_familiarity": 1,
		"grants_tension": 0,
		"once_ever": true,
		"zone_type": "fire",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Tamsin Reed", "text": "You keep cooking after days like this." },
			{ "speaker": "Branik", "text": "People still need to eat after bad news." },
			{ "speaker": "Tamsin Reed", "text": "Feels strange to stir stew after stitching wounds." },
			{ "speaker": "Branik", "text": "That's the point. The food says tomorrow is real." },
		],
	},
	{
		"id": "oren_rufus_wall_scene",
		"priority": 37,
		"when": { "time_block": "day" },
		"unit_a": "Oren Pike",
		"unit_b": "Rufus",
		"zone_type": "wall",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Oren Pike", "text": "Lean on that brace again. If it holds you, it'll hold a charge." },
			{ "speaker": "Rufus", "text": "You test defenses with dock muscle. Charming." },
			{ "speaker": "Oren Pike", "text": "If the wall complains now, we fix it. If it complains later, we bury people." },
			{ "speaker": "Rufus", "text": "Fine. I'll argue with the stone so the troops don't have to." },
		],
	},
	{
		"id": "meris_liora_shrine_scene",
		"priority": 39,
		"when": { "time_block": "day" },
		"unit_a": "Sister Meris",
		"unit_b": "Liora",
		"zone_type": "shrine",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Sister Meris", "text": "I used to think these stones made prayers heavier." },
			{ "speaker": "Liora", "text": "I keep hoping they can make regret lighter." },
			{ "speaker": "Sister Meris", "text": "You still trust the words?" },
			{ "speaker": "Liora", "text": "Not all of them. Just the ones we write again, kinder." },
		],
	},
	{
		"id": "corvin_sorrel_wagon_scene",
		"priority": 39,
		"when": { "time_block": "night" },
		"unit_a": "Corvin Ash",
		"unit_b": "Sorrel",
		"zone_type": "wagon",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Sorrel", "text": "You catalog horrors like they're footnotes." },
			{ "speaker": "Corvin Ash", "text": "Footnotes are where people hide the real crimes." },
			{ "speaker": "Sorrel", "text": "Comforting thought before sleep." },
			{ "speaker": "Corvin Ash", "text": "Sleep is for the innocent. Accuracy is for the rest of us." },
		],
	},
	{
		"id": "veska_garrick_watch_scene",
		"priority": 38,
		"when": { "time_block": "night" },
		"unit_a": "Veska Moor",
		"unit_b": "Garrick Vale",
		"zone_type": "watch_post",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Veska Moor", "text": "Your lines on the map end here. Mine end at the shield rim." },
			{ "speaker": "Garrick Vale", "text": "Both are still trying to keep the same people standing." },
			{ "speaker": "Veska Moor", "text": "Then draw your arrows where I can see them, commander." },
			{ "speaker": "Garrick Vale", "text": "Agreed. No surprises at the wall if I can help it." },
		],
	},
	{
		"id": "inez_mira_tree_scene",
		"priority": 37,
		"when": { "time_block": "night" },
		"unit_a": "Inez",
		"unit_b": "Mira Ashdown",
		"zone_type": "tree_line",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Inez", "text": "You stare at the dark like it's an old argument." },
			{ "speaker": "Mira Ashdown", "text": "It took everything from me. I reserve the right to glare back." },
			{ "speaker": "Inez", "text": "Good. Ruins should know when they're being watched too." },
		],
	},
	{
		"id": "kaelen_celia_watch_followup_1",
		"priority": 44,
		"when": { "time_block": "dawn" },
		"unit_a": "Kaelen",
		"unit_b": "Celia",
		"min_familiarity": 1,
		"grants_familiarity": 1,
		"grants_tension": 0,
		"once_ever": true,
		"zone_type": "watch_post",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Celia", "text": "You don't correct my stance anymore." },
			{ "speaker": "Kaelen", "text": "Because you corrected it yourself." },
			{ "speaker": "Celia", "text": "Try not to sound proud of me in public." },
			{ "speaker": "Kaelen", "text": "Then keep giving me reasons in private." },
		],
	},
	{
		"id": "sorrel_tariq_map_followup_1",
		"priority": 44,
		"when": { "time_block": "day" },
		"unit_a": "Sorrel",
		"unit_b": "Tariq",
		"min_familiarity": 1,
		"grants_familiarity": 1,
		"grants_tension": 0,
		"once_ever": true,
		"zone_type": "map_table",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Tariq", "text": "You stopped writing jokes in the margins." },
			{ "speaker": "Sorrel", "text": "You started reading them correctly." },
			{ "speaker": "Tariq", "text": "A dangerous development." },
			{ "speaker": "Sorrel", "text": "Then we're finally making progress." },
		],
	},
	{
		"id": "tamsin_branik_fire_followup_1",
		"priority": 44,
		"when": { "time_block": "night" },
		"unit_a": "Tamsin Reed",
		"unit_b": "Branik",
		"min_familiarity": 1,
		"grants_familiarity": 1,
		"grants_tension": 0,
		"once_ever": true,
		"zone_type": "fire",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Branik", "text": "You ate before everyone else for once." },
			{ "speaker": "Tamsin Reed", "text": "Don't make a ceremony of it." },
			{ "speaker": "Branik", "text": "No ceremony. Just less worrying." },
			{ "speaker": "Tamsin Reed", "text": "Fine. I'll consider that a shared victory." },
		],
	},
	{
		"id": "kaelen_celia_tense_watch_variant",
		"preferred_visit_themes": ["tense"],
		"priority": 43,
		"when": { "time_block": "dawn" },
		"moods": ["tense"],
		"unit_a": "Kaelen",
		"unit_b": "Celia",
		"min_familiarity": 1,
		"grants_familiarity": 1,
		"grants_tension": 0,
		"once_ever": true,
		"zone_type": "watch_post",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Kaelen", "text": "No wasted words today." },
			{ "speaker": "Celia", "text": "Then point and trust me." },
			{ "speaker": "Kaelen", "text": "I do. Move." },
		],
	},
	{
		"id": "liora_alden_somber_infirmary_variant",
		"preferred_visit_themes": ["somber", "recovery"],
		"priority": 42,
		"when": { "time_block": "day" },
		"moods": ["somber"],
		"unit_a": "Liora",
		"unit_b": "Brother Alden",
		"grants_familiarity": 1,
		"grants_tension": 0,
		"once_ever": true,
		"zone_type": "infirmary",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Brother Alden", "text": "You can sit for one breath." },
			{ "speaker": "Liora", "text": "One breath, then back to it." },
			{ "speaker": "Brother Alden", "text": "That is enough for now." },
		],
	},
	{
		"id": "tamsin_branik_recovery_scene",
		"preferred_visit_themes": ["recovery"],
		"priority": 46,
		"when": { "time_block": "night" },
		"unit_a": "Tamsin Reed",
		"unit_b": "Branik",
		"requires_injured_speaker": true,
		"grants_familiarity": 1,
		"grants_tension": 0,
		"once_ever": true,
		"zone_type": "fire",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Branik", "text": "You wrapped that arm too tight." },
			{ "speaker": "Tamsin Reed", "text": "It stops me from pretending it's fine." },
			{ "speaker": "Branik", "text": "Good. Pretend less. Eat more." },
		],
	},
	{
		"id": "liora_alden_fatigue_scene",
		"priority": 45,
		"when": { "time_block": "day" },
		"unit_a": "Brother Alden",
		"unit_b": "Liora",
		"requires_fatigued_listener": true,
		"grants_familiarity": 1,
		"grants_tension": 0,
		"once_ever": true,
		"zone_type": "infirmary",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Brother Alden", "text": "You're counting steps between patients now." },
			{ "speaker": "Liora", "text": "If I stop counting, I stop moving." },
			{ "speaker": "Brother Alden", "text": "Then count one rest before the next round." },
		],
	},
	{
		"id": "pell_rufus_workbench_scene",
		"priority": 38,
		"when": { "time_block": "day" },
		"unit_a": "Pell Rowan",
		"unit_b": "Rufus",
		"zone_type": "workbench",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Pell Rowan", "text": "I keep over-tightening this bracket." },
			{ "speaker": "Rufus", "text": "You're trying to beat fear, not the metal. Slow down." },
			{ "speaker": "Pell Rowan", "text": "Right. Steady first, heroic second." },
			{ "speaker": "Rufus", "text": "Now you're learning the useful kind of bravery." },
		],
	},
	{
		"id": "maela_mira_watch_scene",
		"priority": 38,
		"when": { "time_block": "dawn" },
		"unit_a": "Maela Thorn",
		"unit_b": "Mira Ashdown",
		"zone_type": "watch_post",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Maela Thorn", "text": "You always spot movement before I call it." },
			{ "speaker": "Mira Ashdown", "text": "You always get there before anyone else can worry." },
			{ "speaker": "Maela Thorn", "text": "That sounded like a compliment." },
			{ "speaker": "Mira Ashdown", "text": "Keep it. Don't get reckless with it." },
		],
	},
	{
		"id": "hadrien_kaelen_shrine_scene",
		"priority": 40,
		"when": { "time_block": "night" },
		"unit_a": "Ser Hadrien",
		"unit_b": "Kaelen",
		"zone_type": "shrine",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Ser Hadrien", "text": "We trained boys to become vows." },
			{ "speaker": "Kaelen", "text": "And spent the rest of our lives teaching them to survive the vows." },
			{ "speaker": "Ser Hadrien", "text": "Then perhaps we owe this camp honesty, not legend." },
			{ "speaker": "Kaelen", "text": "For once, we agree without a sword between us." },
		],
	},
	{
		"id": "sabine_veska_wall_scene",
		"priority": 38,
		"when": { "time_block": "day" },
		"unit_a": "Sabine Varr",
		"unit_b": "Veska Moor",
		"zone_type": "wall",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Sabine Varr", "text": "You rotate shields before the horn. Good." },
			{ "speaker": "Veska Moor", "text": "You rotate sentries before they complain. Also good." },
			{ "speaker": "Sabine Varr", "text": "Efficiency is a language I trust." },
			{ "speaker": "Veska Moor", "text": "Then we are speaking clearly." },
		],
	},
	{
		"id": "yselle_darian_fire_scene",
		"priority": 37,
		"when": { "time_block": "night" },
		"unit_a": "Yselle Maris",
		"unit_b": "Darian",
		"zone_type": "fire",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Yselle Maris", "text": "You smile like applause is mandatory." },
			{ "speaker": "Darian", "text": "Only when the critic is this sharp." },
			{ "speaker": "Yselle Maris", "text": "Good. Then let the camp breathe before your next performance." },
			{ "speaker": "Darian", "text": "Tonight I can manage sincerity instead." },
		],
	},
	{
		"id": "inez_corvin_tree_scene",
		"priority": 39,
		"when": { "time_block": "night" },
		"unit_a": "Inez",
		"unit_b": "Corvin Ash",
		"zone_type": "tree_line",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Inez", "text": "You ask the dark for answers like it owes you." },
			{ "speaker": "Corvin Ash", "text": "No. I ask because silence has killed more than curiosity." },
			{ "speaker": "Inez", "text": "Then ask without carving wounds into living ground." },
			{ "speaker": "Corvin Ash", "text": "Agreed. Your forest keeps stricter terms than any archive." },
		],
	},
	{
		"id": "hadrien_meris_shrine_scene",
		"priority": 39,
		"when": { "time_block": "night" },
		"unit_a": "Ser Hadrien",
		"unit_b": "Sister Meris",
		"zone_type": "shrine",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Sister Meris", "text": "I spent years mistaking certainty for virtue." },
			{ "speaker": "Ser Hadrien", "text": "Then begin with doubt honestly held. It is cleaner steel." },
			{ "speaker": "Sister Meris", "text": "You speak as if absolution is procedural." },
			{ "speaker": "Ser Hadrien", "text": "No. Only service is. Absolution follows slower." },
		],
	},
	{
		"id": "pell_mira_watch_scene",
		"priority": 38,
		"when": { "time_block": "dawn" },
		"unit_a": "Pell Rowan",
		"unit_b": "Mira Ashdown",
		"zone_type": "watch_post",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Pell Rowan", "text": "I keep rehearsing the callouts and still trip over them." },
			{ "speaker": "Mira Ashdown", "text": "Then use fewer words. Make the first one true." },
			{ "speaker": "Pell Rowan", "text": "Right. True first. Fancy later." },
			{ "speaker": "Mira Ashdown", "text": "Later can wait. Dawn won't." },
		],
	},
	{
		"id": "veska_oren_wall_scene",
		"priority": 38,
		"when": { "time_block": "day" },
		"unit_a": "Veska Moor",
		"unit_b": "Oren Pike",
		"zone_type": "wall",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Oren Pike", "text": "Brace is holding, but this corner still groans." },
			{ "speaker": "Veska Moor", "text": "Then I stand here until it learns manners." },
			{ "speaker": "Oren Pike", "text": "I'd prefer timber over heroics." },
			{ "speaker": "Veska Moor", "text": "Good. Bring timber. I'll keep the corner honest." },
		],
	},
	{
		"id": "pair_progress_mid_nyx_sorrel_map_scene",
		"priority": 37,
		"when": { "time_block": "day" },
		"min_progress_level": 9,
		"max_progress_level": 13,
		"unit_a": "Nyx",
		"unit_b": "Sorrel",
		"zone_type": "map_table",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"lines": [
			{ "speaker": "Nyx", "text": "Funny how plans get cleaner right before they go bad." },
			{ "speaker": "Sorrel", "text": "That is why contingency is not pessimism." },
			{ "speaker": "Nyx", "text": "Keep talking like that and I'll start trusting the paperwork." },
		],
	},
	{
		"id": "pair_progress_late_hadrien_kaelen_shrine_scene",
		"priority": 40,
		"when": { "time_block": "night" },
		"min_progress_level": 16,
		"unit_a": "Ser Hadrien",
		"unit_b": "Kaelen",
		"zone_type": "shrine",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"once_ever": true,
		"lines": [
			{ "speaker": "Kaelen", "text": "I used to think resolve was loud." },
			{ "speaker": "Ser Hadrien", "text": "Resolve is quiet. Duty is what hears it." },
			{ "speaker": "Kaelen", "text": "Then let's make sure the others only hear the part that helps." },
		],
	},
	{
		"id": "darian_pell_bench_scene",
		"priority": 37,
		"when": { "time_block": "day" },
		"unit_a": "Darian",
		"unit_b": "Pell Rowan",
		"zone_type": "bench",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"once_ever": true,
		"grants_familiarity": 1,
		"grants_tension": 0,
		"lines": [
			{ "speaker": "Pell Rowan", "text": "Do I look ridiculous when I try to sit like a knight?" },
			{ "speaker": "Darian", "text": "Only when you try. The trick is to look comfortable before you earn it." },
			{ "speaker": "Pell Rowan", "text": "That sounds dishonest." },
			{ "speaker": "Darian", "text": "No. It is mercy toward the terrified version of yourself." },
		],
	},
	{
		"id": "rufus_oren_workbench_scene",
		"priority": 37,
		"when": { "time_block": "day" },
		"unit_a": "Rufus",
		"unit_b": "Oren Pike",
		"zone_type": "workbench",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"once_ever": true,
		"grants_familiarity": 1,
		"grants_tension": 0,
		"lines": [
			{ "speaker": "Oren Pike", "text": "You ever notice nobody praises the brace that holds?" },
			{ "speaker": "Rufus", "text": "Same reason nobody thanks the dock when the ship floats. Means it did its job." },
			{ "speaker": "Oren Pike", "text": "Still irritating." },
			{ "speaker": "Rufus", "text": "Naturally. That is how I know you are healthy." },
		],
	},
	{
		"id": "inez_maela_tree_scene",
		"priority": 38,
		"when": { "time_block": "day" },
		"unit_a": "Inez",
		"unit_b": "Maela Thorn",
		"zone_type": "tree_line",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"once_ever": true,
		"grants_familiarity": 1,
		"grants_tension": 0,
		"lines": [
			{ "speaker": "Maela Thorn", "text": "You know, one day I am going to make it through those trees without you hearing me." },
			{ "speaker": "Inez", "text": "When that day comes, I will stop calling you reckless and start calling you useful." },
			{ "speaker": "Maela Thorn", "text": "That is the nicest thing you have ever threatened me with." },
		],
	},
	{
		"id": "alden_meris_shrine_scene",
		"priority": 39,
		"when": { "time_block": "night" },
		"min_progress_level": 7,
		"unit_a": "Brother Alden",
		"unit_b": "Sister Meris",
		"zone_type": "shrine",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"once_ever": true,
		"grants_familiarity": 1,
		"grants_tension": 0,
		"lines": [
			{ "speaker": "Sister Meris", "text": "I remember every order I carried out cleanly. That is the worst part." },
			{ "speaker": "Brother Alden", "text": "Memory can wound. It can also keep the hand from becoming careless again." },
			{ "speaker": "Sister Meris", "text": "You make repentance sound almost practical." },
			{ "speaker": "Brother Alden", "text": "For the living, it is." },
		],
	},
	{
		"id": "yselle_sabine_bench_scene",
		"priority": 37,
		"when": { "time_block": "day" },
		"unit_a": "Yselle Maris",
		"unit_b": "Sabine Varr",
		"zone_type": "bench",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"once_ever": true,
		"grants_familiarity": 1,
		"grants_tension": 0,
		"lines": [
			{ "speaker": "Yselle Maris", "text": "You do realize half the camp finds you reassuring by accident." },
			{ "speaker": "Sabine Varr", "text": "An alarming sentence already." },
			{ "speaker": "Yselle Maris", "text": "They see someone who notices danger before it reaches them." },
			{ "speaker": "Sabine Varr", "text": "That is merely competence." },
			{ "speaker": "Yselle Maris", "text": "Exactly. Some people call that comfort." },
		],
	},
	{
		"id": "hadrien_kaelen_watch_scene",
		"priority": 40,
		"when": { "time_block": "night" },
		"min_progress_level": 12,
		"unit_a": "Ser Hadrien",
		"unit_b": "Kaelen",
		"zone_type": "watch_post",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"once_ever": true,
		"grants_familiarity": 1,
		"grants_tension": 0,
		"lines": [
			{ "speaker": "Kaelen", "text": "Sometimes I look at you and remember how young we all thought old knights were." },
			{ "speaker": "Ser Hadrien", "text": "Age is not the sorrow, Kaelen. Outliving the use of what you were taught is." },
			{ "speaker": "Kaelen", "text": "Then we teach the young better and call that revenge." },
			{ "speaker": "Ser Hadrien", "text": "A stern and worthy form of it." },
		],
	},
	{
		"id": "corvin_meris_shrine_scene",
		"priority": 38,
		"when": { "time_block": "night" },
		"min_progress_level": 7,
		"unit_a": "Corvin Ash",
		"unit_b": "Sister Meris",
		"zone_type": "shrine",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"once_ever": true,
		"grants_familiarity": 1,
		"grants_tension": 1,
		"lines": [
			{ "speaker": "Corvin Ash", "text": "You still sort truths into clean and unclean categories." },
			{ "speaker": "Sister Meris", "text": "And you speak as if contamination were a form of wisdom." },
			{ "speaker": "Corvin Ash", "text": "No. Only contact. The world is rarely cleansed by refusal to look at it." },
			{ "speaker": "Sister Meris", "text": "Perhaps. But some things become easier to justify the longer one stares." },
		],
	},
	{
		"id": "garrick_celia_wall_scene",
		"priority": 37,
		"when": { "time_block": "dawn" },
		"unit_a": "Garrick Vale",
		"unit_b": "Celia",
		"zone_type": "wall",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"once_ever": true,
		"grants_familiarity": 1,
		"grants_tension": 0,
		"lines": [
			{ "speaker": "Garrick Vale", "text": "You carry duty like armor. It will serve you less well if you never take it off." },
			{ "speaker": "Celia", "text": "I am still learning who I am when I do not wear it." },
			{ "speaker": "Garrick Vale", "text": "Then learn slowly. Better that than never." },
		],
	},
	{
		"id": "branik_inez_supply_scene",
		"priority": 36,
		"when": { "time_block": "day" },
		"unit_a": "Branik",
		"unit_b": "Inez",
		"zone_type": "supply",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"once_ever": true,
		"grants_familiarity": 1,
		"grants_tension": 0,
		"lines": [
			{ "speaker": "Inez", "text": "You portion rations like a forester cutting winter stores." },
			{ "speaker": "Branik", "text": "Hungry people think poorly. I would rather they think well." },
			{ "speaker": "Inez", "text": "Practical answer." },
			{ "speaker": "Branik", "text": "Most useful ones are." },
		],
	},
	{
		"id": "mira_pell_watch_scene",
		"priority": 36,
		"when": { "time_block": "dawn" },
		"max_progress_level": 6,
		"unit_a": "Mira Ashdown",
		"unit_b": "Pell Rowan",
		"zone_type": "watch_post",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"once_ever": true,
		"grants_familiarity": 1,
		"grants_tension": 0,
		"lines": [
			{ "speaker": "Pell Rowan", "text": "Do you ever stop feeling nervous before watch?" },
			{ "speaker": "Mira Ashdown", "text": "No. I just stopped waiting for that to be required." },
			{ "speaker": "Pell Rowan", "text": "That is not as comforting as I hoped." },
			{ "speaker": "Mira Ashdown", "text": "It is still useful." },
		],
	},
	{
		"id": "pair_theme_training_sabine_pell_wall",
		"priority": 37,
		"when": { "time_block": "day" },
		"unit_a": "Sabine Varr",
		"unit_b": "Pell Rowan",
		"preferred_visit_themes": ["training"],
		"zone_type": "wall",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"once_ever": true,
		"grants_familiarity": 1,
		"grants_tension": 0,
		"lines": [
			{ "speaker": "Sabine Varr", "text": "Your shield checks are improving. Do not get sentimental about good habits." },
			{ "speaker": "Pell Rowan", "text": "I will save sentiment for after I survive the habit." },
			{ "speaker": "Sabine Varr", "text": "Fair. Sentiment after survival is called discipline with a pulse." },
		],
	},
	{
		"id": "pair_theme_gossip_corvin_nyx_wagon",
		"priority": 36,
		"when": { "time_block": "night" },
		"unit_a": "Corvin Ash",
		"unit_b": "Nyx",
		"preferred_visit_themes": ["gossip", "tense"],
		"zone_type": "wagon",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"once_ever": true,
		"grants_familiarity": 1,
		"grants_tension": 0,
		"lines": [
			{ "speaker": "Nyx", "text": "Camp thinks your ledgers are bedtime stories." },
			{ "speaker": "Corvin Ash", "text": "Only the dull pages. The interesting ones keep people awake on purpose." },
			{ "speaker": "Nyx", "text": "Comforting. I prefer insomnia with citations." },
		],
	},
	{
		"id": "pair_theme_hopeful_branik_liora_cook",
		"priority": 36,
		"when": { "time_block": "day" },
		"unit_a": "Branik",
		"unit_b": "Liora",
		"preferred_visit_themes": ["hopeful", "recovery"],
		"zone_type": "cook_area",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"once_ever": true,
		"grants_familiarity": 1,
		"grants_tension": 0,
		"lines": [
			{ "speaker": "Liora", "text": "You measure salt like you're negotiating peace." },
			{ "speaker": "Branik", "text": "Bad soup makes worse treaties. I'm biased toward outcomes." },
			{ "speaker": "Liora", "text": "Then pour. I'll bless the pot after, not before." },
		],
	},
	{
		"id": "pair_theme_somber_maela_inez_tree",
		"priority": 37,
		"when": { "time_block": "night" },
		"unit_a": "Maela Thorn",
		"unit_b": "Inez",
		"preferred_visit_themes": ["somber"],
		"zone_type": "tree_line",
		"pair_radius": 90.0,
		"once_per_visit": true,
		"once_ever": true,
		"grants_familiarity": 1,
		"grants_tension": 0,
		"lines": [
			{ "speaker": "Maela Thorn", "text": "Some nights the trees sound like they're counting us." },
			{ "speaker": "Inez", "text": "Let them count. Means we're still here to be worth inventory." },
			{ "speaker": "Maela Thorn", "text": "Grim comfort." },
			{ "speaker": "Inez", "text": "Best kind. Doesn't spoil." },
		],
	},
]

static func get_all_trigger_scenes() -> Array:
	return TRIGGER_SCENES

static func when_matches(scene: Dictionary, context: Dictionary) -> bool:
	if not scene is Dictionary or not context is Dictionary:
		return false
	var when: Variant = scene.get("when", null)
	if when != null and when is Dictionary:
		var want_tb: String = str((when as Dictionary).get("time_block", "")).strip_edges().to_lower()
		if not want_tb.is_empty():
			var ctx_tb: String = str(context.get("time_block", "")).strip_edges().to_lower()
			if ctx_tb != want_tb:
				return false
	if scene.has("moods"):
		var moods_v: Variant = scene.get("moods", [])
		if moods_v is Array:
			var want_mood: String = str(context.get("camp_mood", "normal")).strip_edges().to_lower()
			var allowed: Array = moods_v
			var matched: bool = false
			for m in allowed:
				if str(m).strip_edges().to_lower() == want_mood:
					matched = true
					break
			if not matched:
				return false
	if not _story_progress_matches(scene, context):
		return false
	return true

static func _story_progress_matches(entry: Dictionary, context: Dictionary) -> bool:
	var progress_level: int = int(context.get("progress_level", 0))
	var min_level: int = int(entry.get("min_progress_level", -1))
	if min_level >= 0 and progress_level < min_level:
		return false
	var max_level: int = int(entry.get("max_progress_level", -1))
	if max_level >= 0 and progress_level > max_level:
		return false
	var flags_v: Variant = context.get("story_flags", {})
	var story_flags: Dictionary = flags_v if flags_v is Dictionary else {}
	var req_v: Variant = entry.get("required_story_flags", [])
	if req_v is Array:
		for token_v in (req_v as Array):
			var token: String = str(token_v).strip_edges()
			if token == "":
				continue
			if not bool(story_flags.get(token, false)):
				return false
	var block_v: Variant = entry.get("blocked_story_flags", [])
	if block_v is Array:
		for token_v2 in (block_v as Array):
			var token2: String = str(token_v2).strip_edges()
			if token2 == "":
				continue
			if bool(story_flags.get(token2, false)):
				return false
	return true
