class_name CampMicroBarkDB

const MICRO_BARK_DEFAULT_RADIUS: float = 140.0
const MICRO_BARK_DEFAULT_PAIR_RADIUS: float = 80.0

const MICRO_BARKS: Array = [
	{
		"id": "kaelen_celia_watch_dawn",
		"preferred_visit_themes": ["training", "tense"],
		"priority": 12,
		"when": { "time_block": "dawn" },
		"speaker": "Kaelen",
		"listener": "Celia",
		"zone_type": "watch_post",
		"text": "\"East torches first.\" — \"Done before you finished giving the order.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "sorrel_tariq_map_day",
		"priority": 11,
		"when": { "time_block": "day" },
		"speaker": "Sorrel",
		"listener": "Tariq",
		"zone_type": "map_table",
		"text": "\"Your notes are worse than the roads.\" — \"And yet still more reliable.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "branik_darian_fire_night",
		"preferred_visit_themes": ["normal", "hopeful"],
		"priority": 11,
		"when": { "time_block": "night" },
		"speaker": "Branik",
		"listener": "Darian",
		"zone_type": "fire",
		"text": "\"If you sing, sing after the stew.\" — \"No promises.\"",
		"once_per_visit": false,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "rufus_hest_workbench_day",
		"priority": 11,
		"when": { "time_block": "day" },
		"speaker": "Rufus",
		"listener": "Hest \"Sparks\"",
		"zone_type": "workbench",
		"text": "\"Hand me the proper tool.\" — \"You say that like I'd hand you the wrong one.\"",
		"once_per_visit": false,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "liora_brother_alden_infirmary_day",
		"priority": 11,
		"when": { "time_block": "day" },
		"speaker": "Liora",
		"listener": "Brother Alden",
		"zone_type": "infirmary",
		"text": "\"You should rest.\" — \"After the wounded do.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "liora_brother_alden_shrine_day",
		"priority": 11,
		"when": { "time_block": "day" },
		"speaker": "Liora",
		"listener": "Brother Alden",
		"zone_type": "shrine",
		"text": "\"The votives need trimming—half the wax is honest prayer, half is guilt.\" — \"Then leave the honest half. I will deal with mine in daylight.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "garrick_sabine_wall_day",
		"preferred_visit_themes": ["tense", "training"],
		"priority": 10,
		"when": { "time_block": "day" },
		"speaker": "Garrick Vale",
		"listener": "Sabine Varr",
		"zone_type": "wall",
		"text": "\"Any weakness?\" — \"Not if I see it first.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "nyx_mira_tree_night",
		"preferred_visit_themes": ["tense", "gossip"],
		"priority": 11,
		"when": { "time_block": "night" },
		"speaker": "Nyx",
		"listener": "Mira Ashdown",
		"zone_type": "tree_line",
		"text": "\"You heard that too.\" — \"I heard three things.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "nyx_hest_workbench_day",
		"priority": 11,
		"when": { "time_block": "day" },
		"speaker": "Nyx",
		"listener": "Hest \"Sparks\"",
		"zone_type": "workbench",
		"text": "\"If it goes boom, I blame you.\" — \"Then you'll be right for once.\"",
		"once_per_visit": false,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "tamsin_branik_fire_night",
		"preferred_visit_themes": ["hopeful", "recovery"],
		"priority": 11,
		"when": { "time_block": "night" },
		"speaker": "Tamsin Reed",
		"listener": "Branik",
		"zone_type": "fire",
		"text": "\"You keep feeding everyone.\" — \"You keep them alive to eat. Seems fair.\"",
		"once_per_visit": false,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "oren_rufus_workbench_day",
		"priority": 10,
		"when": { "time_block": "day" },
		"speaker": "Oren Pike",
		"listener": "Rufus",
		"zone_type": "workbench",
		"text": "\"Lift with your legs.\" — \"I am. The crate is just stubborn.\"",
		"once_per_visit": false,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "oren_rufus_wall_day",
		"priority": 10,
		"when": { "time_block": "day" },
		"speaker": "Oren Pike",
		"listener": "Rufus",
		"zone_type": "wall",
		"text": "\"Push there.\" — \"You engineers always say that right before something settles or breaks.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "meris_liora_shrine_day",
		"priority": 11,
		"when": { "time_block": "day" },
		"speaker": "Sister Meris",
		"listener": "Liora",
		"zone_type": "shrine",
		"text": "\"You still believe in lighting candles?\" — \"I believe in people seeing each other in the light.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "corvin_sorrel_map_day",
		"priority": 11,
		"when": { "time_block": "day" },
		"speaker": "Corvin Ash",
		"listener": "Sorrel",
		"zone_type": "map_table",
		"text": "\"You annotated the dangers.\" — \"You edited out the lies.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "veska_garrick_wall_day",
		"priority": 10,
		"when": { "time_block": "day" },
		"speaker": "Veska Moor",
		"listener": "Garrick Vale",
		"zone_type": "wall",
		"text": "\"Your plan holds on paper.\" — \"Yours holds the wall. I'll take both.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "inez_mira_tree_night_quiet",
		"priority": 10,
		"when": { "time_block": "night" },
		"speaker": "Inez",
		"listener": "Mira Ashdown",
		"zone_type": "tree_line",
		"text": "\"You like the edge of camp.\" — \"It's where things admit what they are.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "maela_pell_watch_dawn",
		"priority": 10,
		"when": { "time_block": "dawn" },
		"speaker": "Maela Thorn",
		"listener": "Pell Rowan",
		"zone_type": "watch_post",
		"text": "\"Still rehearsing speeches?\" — \"Only the parts where I don't trip over words.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "tariq_meris_map_day",
		"priority": 10,
		"when": { "time_block": "day" },
		"speaker": "Tariq",
		"listener": "Sister Meris",
		"zone_type": "map_table",
		"text": "\"You question doctrine on a map.\" — \"Ink is safer than stone for that.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "celia_pell_bench_dawn",
		"priority": 9,
		"when": { "time_block": "dawn" },
		"speaker": "Celia",
		"listener": "Pell Rowan",
		"zone_type": "bench",
		"text": "\"Back straight.\" — \"Even while sitting?\"",
		"once_per_visit": false,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "kaelen_celia_watch_familiar",
		"priority": 13,
		"when": { "time_block": "dawn" },
		"speaker": "Kaelen",
		"listener": "Celia",
		"zone_type": "watch_post",
		"min_familiarity": 1,
		"text": "\"You checked your own line this time.\" — \"Try not to sound surprised.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "sorrel_tariq_map_familiar",
		"priority": 13,
		"when": { "time_block": "day" },
		"speaker": "Sorrel",
		"listener": "Tariq",
		"zone_type": "map_table",
		"min_familiarity": 1,
		"text": "\"You finally trust my shortcuts.\" — \"I trust your odds. Barely.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "tamsin_branik_fire_familiar",
		"priority": 13,
		"when": { "time_block": "night" },
		"speaker": "Tamsin Reed",
		"listener": "Branik",
		"zone_type": "fire",
		"min_familiarity": 1,
		"text": "\"You saved me a bowl again.\" — \"I saved two. I learn.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "nyx_hest_workbench_familiar",
		"priority": 12,
		"when": { "time_block": "day" },
		"speaker": "Nyx",
		"listener": "Hest \"Sparks\"",
		"zone_type": "workbench",
		"min_familiarity": 1,
		"text": "\"I labeled your fuses.\" — \"That's either trust or an accusation.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "nyx_hest_workbench_recent",
		"priority": 14,
		"when": { "time_block": "day" },
		"speaker": "Hest \"Sparks\"",
		"listener": "Nyx",
		"zone_type": "workbench",
		"recent_within_visits": 1,
		"text": "\"Back already?\" — \"You left me three unfinished warnings.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "sorrel_tariq_map_recent",
		"priority": 14,
		"when": { "time_block": "day" },
		"speaker": "Tariq",
		"listener": "Sorrel",
		"zone_type": "map_table",
		"recent_within_visits": 1,
		"text": "\"Where did we stop arguing?\" — \"At the useful part.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "garrick_sabine_wall_tension",
		"priority": 12,
		"when": { "time_block": "day" },
		"speaker": "Garrick Vale",
		"listener": "Sabine Varr",
		"zone_type": "wall",
		"min_tension": 1,
		"text": "\"Report plain.\" — \"Then give plain orders.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "kaelen_celia_watch_tension",
		"priority": 12,
		"when": { "time_block": "dawn" },
		"speaker": "Celia",
		"listener": "Kaelen",
		"zone_type": "watch_post",
		"min_tension": 1,
		"text": "\"You can critique later.\" — \"Then don't hand me a reason now.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "micro_kaelen_celia_hopeful_watch",
		"preferred_visit_themes": ["hopeful"],
		"priority": 12,
		"when": { "time_block": "dawn" },
		"moods": ["hopeful"],
		"speaker": "Celia",
		"listener": "Kaelen",
		"zone_type": "watch_post",
		"text": "\"No lectures today?\" — \"Only because you don't need one.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "micro_sorrel_tariq_tense_map",
		"preferred_visit_themes": ["tense"],
		"priority": 12,
		"when": { "time_block": "day" },
		"moods": ["tense"],
		"speaker": "Tariq",
		"listener": "Sorrel",
		"zone_type": "map_table",
		"text": "\"Ink only—no flourishes.\" — \"Then I'll sweat in silence and let the line speak.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "micro_tamsin_branik_somber_fire",
		"preferred_visit_themes": ["somber"],
		"priority": 12,
		"when": { "time_block": "night" },
		"moods": ["somber"],
		"speaker": "Branik",
		"listener": "Tamsin Reed",
		"zone_type": "fire",
		"text": "\"Eat.\" — \"Only if you do too.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "micro_darian_yselle_hopeful_fire",
		"priority": 11,
		"when": { "time_block": "night" },
		"moods": ["hopeful"],
		"speaker": "Darian",
		"listener": "Yselle Maris",
		"zone_type": "fire",
		"text": "\"That's almost a smile.\" — \"Don't waste it.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "micro_tamsin_branik_injury_fire",
		"priority": 13,
		"when": { "time_block": "night" },
		"speaker": "Branik",
		"listener": "Tamsin Reed",
		"requires_injured_listener": true,
		"zone_type": "fire",
		"text": "\"Sit.\" — \"I'm working.\" — \"Sit while you work.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "micro_kaelen_celia_fatigued_watch",
		"priority": 13,
		"when": { "time_block": "dawn" },
		"speaker": "Celia",
		"listener": "Kaelen",
		"requires_fatigued_listener": true,
		"zone_type": "watch_post",
		"text": "\"You were up all night.\" — \"Then I'll be awake all dawn too.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "micro_sorrel_tariq_fatigue_map",
		"priority": 13,
		"when": { "time_block": "day" },
		"speaker": "Sorrel",
		"listener": "Tariq",
		"requires_fatigued_speaker": true,
		"zone_type": "map_table",
		"text": "\"My handwriting is drifting.\" — \"Then I'll read slower.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "micro_liora_alden_injured_infirmary",
		"priority": 13,
		"when": { "time_block": "day" },
		"speaker": "Brother Alden",
		"listener": "Liora",
		"requires_injured_listener": true,
		"zone_type": "infirmary",
		"text": "\"You stitched everyone else first.\" — \"Someone had to.\"",
		"once_per_visit": true,
		"radius": 140.0,
		"pair_radius": 80.0,
	},
	{
		"id": "micro_kaelen_celia_wall_day",
		"priority": 11,
		"when": { "time_block": "day" },
		"speaker": "Kaelen",
		"listener": "Celia",
		"zone_type": "wall",
		"text": "\"Breathe and scan.\" — \"I can do both without permission.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "micro_sorrel_tariq_bench_night",
		"priority": 11,
		"when": { "time_block": "night" },
		"speaker": "Tariq",
		"listener": "Sorrel",
		"zone_type": "bench",
		"text": "\"You marked all the dangerous roads.\" — \"No, only the honest ones.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "micro_nyx_hest_fire_night",
		"priority": 11,
		"when": { "time_block": "night" },
		"speaker": "Nyx",
		"listener": "Hest \"Sparks\"",
		"zone_type": "fire",
		"text": "\"You smell like powder.\" — \"You smell like trouble. We all contribute.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "micro_liora_alden_fire_night",
		"priority": 11,
		"when": { "time_block": "night" },
		"speaker": "Brother Alden",
		"listener": "Liora",
		"zone_type": "fire",
		"text": "\"You finally sat.\" — \"Only long enough for you to stop asking.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "micro_branik_tamsin_infirmary_day",
		"priority": 11,
		"when": { "time_block": "day" },
		"speaker": "Tamsin Reed",
		"listener": "Branik",
		"zone_type": "infirmary",
		"text": "\"You brought broth to a triage table.\" — \"I know my audience.\"",
		"once_per_visit": false,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "micro_garrick_sabine_watch_dawn",
		"priority": 11,
		"when": { "time_block": "dawn" },
		"speaker": "Garrick Vale",
		"listener": "Sabine Varr",
		"zone_type": "watch_post",
		"text": "\"You counted the torches twice.\" — \"I only trust numbers that survive dawn.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "micro_pell_rufus_workbench_day",
		"priority": 10,
		"when": { "time_block": "day" },
		"speaker": "Pell Rowan",
		"listener": "Rufus",
		"zone_type": "workbench",
		"text": "\"Is this brace straight?\" — \"It's straighter than your apology voice.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "micro_maela_mira_watch_dawn",
		"priority": 10,
		"when": { "time_block": "dawn" },
		"speaker": "Maela Thorn",
		"listener": "Mira Ashdown",
		"zone_type": "watch_post",
		"text": "\"You never miss.\" — \"I miss panic. That's enough.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "micro_hadrien_kaelen_shrine_night",
		"priority": 11,
		"when": { "time_block": "night" },
		"speaker": "Ser Hadrien",
		"listener": "Kaelen",
		"zone_type": "shrine",
		"text": "\"You still keep watch as if dawn can be ordered.\" — \"Old habits outlive old wars.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "micro_veska_oren_wall_day",
		"priority": 10,
		"when": { "time_block": "day" },
		"speaker": "Veska Moor",
		"listener": "Oren Pike",
		"zone_type": "wall",
		"text": "\"Your brace holds.\" — \"Your shield does too. I'll call it a fair camp.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "micro_meris_corvin_shrine_night",
		"priority": 10,
		"when": { "time_block": "night" },
		"speaker": "Sister Meris",
		"listener": "Corvin Ash",
		"zone_type": "shrine",
		"text": "\"You catalog ashes like they are scripture.\" — \"Some scriptures were ash first.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "micro_inez_corvin_tree_night",
		"priority": 11,
		"when": { "time_block": "night" },
		"speaker": "Inez",
		"listener": "Corvin Ash",
		"zone_type": "tree_line",
		"text": "\"The trees don't trust you.\" — \"They are wiser than most courts.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "micro_corvin_hadrien_shrine_night",
		"priority": 11,
		"when": { "time_block": "night" },
		"speaker": "Corvin Ash",
		"listener": "Ser Hadrien",
		"zone_type": "shrine",
		"text": "\"You carry a century like a prayer.\" — \"And you carry doubt like incense.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "micro_hadrien_meris_shrine_night",
		"priority": 11,
		"when": { "time_block": "night" },
		"speaker": "Ser Hadrien",
		"listener": "Sister Meris",
		"zone_type": "shrine",
		"text": "\"Judgment bends easier when it kneels first.\" — \"I am still learning how low.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "micro_maela_inez_tree_dawn",
		"priority": 10,
		"when": { "time_block": "dawn" },
		"speaker": "Maela Thorn",
		"listener": "Inez",
		"zone_type": "tree_line",
		"text": "\"You're already awake?\" — \"You are already loud.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "micro_veska_sabine_wall_day",
		"priority": 11,
		"when": { "time_block": "day" },
		"speaker": "Sabine Varr",
		"listener": "Veska Moor",
		"zone_type": "wall",
		"text": "\"You hold like masonry.\" — \"You inspect like prosecution.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "micro_meris_alden_infirmary_day",
		"priority": 10,
		"when": { "time_block": "day" },
		"speaker": "Sister Meris",
		"listener": "Brother Alden",
		"zone_type": "infirmary",
		"text": "\"You forgive too quickly.\" — \"No. I begin quickly.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "micro_pell_mira_watch_dawn",
		"priority": 10,
		"when": { "time_block": "dawn" },
		"speaker": "Pell Rowan",
		"listener": "Mira Ashdown",
		"zone_type": "watch_post",
		"text": "\"Was that call too early?\" — \"Early is fine. Wrong isn't.\"",
		"once_per_visit": false,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "micro_mira_tamsin_infirmary_day",
		"priority": 10,
		"when": { "time_block": "day" },
		"speaker": "Mira Ashdown",
		"listener": "Tamsin Reed",
		"zone_type": "infirmary",
		"text": "\"You can stop apologizing while you bandage.\" — \"I'm trying.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "micro_progress_early_mira_pell",
		"priority": 8,
		"when": { "time_block": "dawn" },
		"min_progress_level": 2,
		"max_progress_level": 6,
		"speaker": "Mira Ashdown",
		"listener": "Pell Rowan",
		"zone_type": "watch_post",
		"text": "\"You're not rushing your draw anymore.\" — \"Because you keep watching.\"",
		"once_per_visit": false,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "micro_progress_mid_garrick_sabine",
		"priority": 8,
		"when": { "time_block": "day" },
		"min_progress_level": 9,
		"max_progress_level": 13,
		"speaker": "Garrick Vale",
		"listener": "Sabine Varr",
		"zone_type": "wall",
		"text": "\"We started this escorting grain.\" — \"Now we're escorting a future.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "micro_progress_late_hadrien_meris",
		"priority": 9,
		"when": { "time_block": "night" },
		"min_progress_level": 16,
		"speaker": "Ser Hadrien",
		"listener": "Sister Meris",
		"zone_type": "shrine",
		"text": "\"Your voice does not shake.\" — \"It did. I learned where to place it.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "bark_branik_rufus_fire_pot",
		"priority": 8,
		"when": { "time_block": "night" },
		"speaker": "Branik",
		"listener": "Rufus",
		"zone_type": "fire",
		"text": "\"If the pot survives you, the cannon will too.\" — \"Pot's got better odds.\"",
		"once_per_visit": false,
		"radius": 150.0,
		"pair_radius": 88.0,
	},
	{
		"id": "bark_branik_alden_fire_wood",
		"priority": 8,
		"when": { "time_block": "night" },
		"speaker": "Branik",
		"listener": "Brother Alden",
		"zone_type": "fire",
		"text": "\"You're carrying wood again.\" — \"Wood complains less than people.\"",
		"once_per_visit": false,
		"radius": 150.0,
		"pair_radius": 88.0,
	},
	{
		"id": "bark_darian_pell_bench_buckle",
		"priority": 7,
		"when": { "time_block": "day" },
		"speaker": "Darian",
		"listener": "Pell Rowan",
		"zone_type": "bench",
		"text": "\"If you polish that buckle any brighter, we'll use it for signaling.\" — \"Then it will be useful twice, sir.\"",
		"once_per_visit": false,
		"radius": 150.0,
		"pair_radius": 88.0,
	},
	{
		"id": "bark_darian_kaelen_fire_music",
		"priority": 8,
		"when": { "time_block": "night" },
		"speaker": "Darian",
		"listener": "Kaelen",
		"zone_type": "fire",
		"text": "\"You glare at music like it insulted your boots.\" — \"Depends on the music.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "bark_rufus_tamsin_fire_numbers",
		"priority": 8,
		"when": { "time_block": "night" },
		"speaker": "Rufus",
		"listener": "Tamsin Reed",
		"zone_type": "fire",
		"text": "\"You need food before numbers.\" — \"I wrote the numbers on the bowl. Efficient, right?\"",
		"once_per_visit": false,
		"radius": 150.0,
		"pair_radius": 88.0,
	},
	{
		"id": "bark_inez_maela_tree_birds",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Inez",
		"listener": "Maela Thorn",
		"zone_type": "tree_line",
		"text": "\"You scare birds for sport.\" — \"Only the arrogant ones.\"",
		"once_per_visit": false,
		"radius": 150.0,
		"pair_radius": 88.0,
	},
	{
		"id": "bark_tariq_liora_bench_footnotes",
		"priority": 7,
		"when": { "time_block": "day" },
		"speaker": "Tariq",
		"listener": "Liora",
		"zone_type": "bench",
		"text": "\"That sermon in your notes had footnotes.\" — \"Mercy deserves citations too.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 88.0,
	},
	{
		"id": "bark_alden_meris_shrine_breath",
		"priority": 8,
		"when": { "time_block": "day" },
		"min_progress_level": 7,
		"speaker": "Brother Alden",
		"listener": "Sister Meris",
		"zone_type": "shrine",
		"text": "\"You are holding your breath again.\" — \"It keeps the hands steady.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 88.0,
	},
	{
		"id": "bark_oren_hest_workbench_wrench",
		"priority": 9,
		"when": { "time_block": "day" },
		"speaker": "Oren Pike",
		"listener": "Hest \"Sparks\"",
		"zone_type": "workbench",
		"text": "\"Hand me the wrench. Not the smoking one.\" — \"You're narrowing it down unfairly.\"",
		"once_per_visit": false,
		"radius": 150.0,
		"pair_radius": 88.0,
	},
	{
		"id": "bark_oren_pell_workbench_hold",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Oren Pike",
		"listener": "Pell Rowan",
		"zone_type": "workbench",
		"text": "\"Hold the brace. Bravery can wait.\" — \"Holding, sir. Very bravely.\"",
		"once_per_visit": false,
		"radius": 150.0,
		"pair_radius": 88.0,
	},
	{
		"id": "bark_garrick_celia_watch_horn",
		"priority": 8,
		"when": { "time_block": "dawn" },
		"speaker": "Garrick Vale",
		"listener": "Celia",
		"zone_type": "watch_post",
		"text": "\"You were awake before the horn.\" — \"The horn was late.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 88.0,
	},
	{
		"id": "bark_garrick_kaelen_watch_line",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Garrick Vale",
		"listener": "Kaelen",
		"zone_type": "watch_post",
		"text": "\"You still pace the same line.\" — \"Means the line still matters.\"",
		"once_per_visit": false,
		"radius": 150.0,
		"pair_radius": 88.0,
	},
	{
		"id": "bark_yselle_liora_fire_ritual",
		"priority": 7,
		"when": { "time_block": "night" },
		"speaker": "Yselle Maris",
		"listener": "Liora",
		"zone_type": "fire",
		"text": "\"You brew tea like a ritual.\" — \"Some rituals are simply kinder than others.\"",
		"once_per_visit": false,
		"radius": 150.0,
		"pair_radius": 88.0,
	},
	{
		"id": "bark_yselle_sabine_bench_inspect",
		"priority": 7,
		"when": { "time_block": "day" },
		"speaker": "Yselle Maris",
		"listener": "Sabine Varr",
		"zone_type": "bench",
		"text": "\"You inspect benches now?\" — \"I inspect anything people might fall off.\"",
		"once_per_visit": false,
		"radius": 150.0,
		"pair_radius": 88.0,
	},
	{
		"id": "bark_veska_sabine_wall_plan",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Veska Moor",
		"listener": "Sabine Varr",
		"zone_type": "wall",
		"text": "\"You tightened that knot twice.\" — \"Once is a prayer. Twice is a plan.\"",
		"once_per_visit": false,
		"radius": 150.0,
		"pair_radius": 88.0,
	},
	{
		"id": "bark_veska_branik_supply_crates",
		"priority": 7,
		"when": { "time_block": "day" },
		"speaker": "Veska Moor",
		"listener": "Branik",
		"zone_type": "supply",
		"text": "\"You lift the heavy crates first too.\" — \"Saves the smaller folk the trouble.\"",
		"once_per_visit": false,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "bark_corvin_meris_shrine_words",
		"priority": 8,
		"when": { "time_block": "night" },
		"min_progress_level": 7,
		"speaker": "Corvin Ash",
		"listener": "Sister Meris",
		"zone_type": "shrine",
		"text": "\"You still flinch at old words.\" — \"I flinch at how easily I believed them.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "bark_hadrien_kaelen_watch_sleep",
		"priority": 8,
		"when": { "time_block": "night" },
		"min_progress_level": 12,
		"speaker": "Ser Hadrien",
		"listener": "Kaelen",
		"zone_type": "watch_post",
		"text": "\"You sleep less than the young think.\" — \"Old habit.\"",
		"once_per_visit": true,
		"radius": 152.0,
		"pair_radius": 90.0,
	},
	{
		"id": "bark_hadrien_maela_tree_landings",
		"priority": 7,
		"when": { "time_block": "day" },
		"min_progress_level": 12,
		"speaker": "Ser Hadrien",
		"listener": "Maela Thorn",
		"zone_type": "tree_line",
		"text": "\"You land like a challenge.\" — \"Better than landing like a warning.\"",
		"once_per_visit": false,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "bark_maela_mira_watch_breaths",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Maela Thorn",
		"listener": "Mira Ashdown",
		"zone_type": "watch_post",
		"text": "\"You count breaths before a shot?\" — \"Better than counting regrets after.\"",
		"once_per_visit": false,
		"radius": 150.0,
		"pair_radius": 88.0,
	},
	{
		"id": "bark_sorrel_liora_shrine_annotations",
		"priority": 7,
		"when": { "time_block": "night" },
		"speaker": "Sorrel",
		"listener": "Liora",
		"zone_type": "shrine",
		"text": "\"You annotate prayers.\" — \"You annotate everything.\"",
		"once_per_visit": false,
		"radius": 150.0,
		"pair_radius": 88.0,
	},
	{
		"id": "bark_rufus_hest_supply_loved_enough",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Rufus",
		"listener": "Hest \"Sparks\"",
		"zone_type": "supply",
		"text": "\"That is not yours.\" — \"It wasn't loved enough where it was.\"",
		"once_per_visit": false,
		"radius": 150.0,
		"pair_radius": 88.0,
	},
	{
		"id": "bark_nyx_rufus_supply_crates_lie",
		"preferred_visit_themes": ["gossip", "tense"],
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Nyx",
		"listener": "Rufus",
		"zone_type": "supply",
		"text": "\"You count crates like you're daring them to lie.\" — \"Crates lie all the time.\"",
		"once_per_visit": false,
		"radius": 150.0,
		"pair_radius": 88.0,
	},
	{
		"id": "bark_mira_tamsin_fire_thread",
		"priority": 7,
		"when": { "time_block": "night" },
		"speaker": "Mira Ashdown",
		"listener": "Tamsin Reed",
		"zone_type": "fire",
		"text": "\"You keep spare thread in your sleeve.\" — \"And you notice everything, apparently.\"",
		"once_per_visit": false,
		"radius": 150.0,
		"pair_radius": 88.0,
	},
	{
		"id": "bark_inez_pell_watch_wind",
		"priority": 7,
		"when": { "time_block": "dawn" },
		"speaker": "Inez",
		"listener": "Pell Rowan",
		"zone_type": "watch_post",
		"text": "\"Stop standing like the wind owes you courtesy.\" — \"I am trying to stand like a knight.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 88.0,
	},
	{
		"id": "bark_rufus_sabine_wall_reports",
		"priority": 7,
		"when": { "time_block": "day" },
		"min_progress_level": 5,
		"speaker": "Rufus",
		"listener": "Sabine Varr",
		"zone_type": "wall",
		"text": "\"You like reports tidy.\" — \"I like disasters smaller than they could have been.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "bark_theme_recovery_alden_liora_fire",
		"priority": 9,
		"when": { "time_block": "night" },
		"speaker": "Brother Alden",
		"listener": "Liora",
		"zone_type": "fire",
		"preferred_visit_themes": ["recovery"],
		"text": "\"Drink before you lecture.\" — \"That's your advice to yourself too.\"",
		"once_per_visit": false,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "bark_theme_gossip_sorrel_darian_bench",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Sorrel",
		"listener": "Darian",
		"zone_type": "bench",
		"preferred_visit_themes": ["gossip"],
		"text": "\"They say you turned down a patron.\" — \"They say a great many flattering things before lunch.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 88.0,
	},
	{
		"id": "bark_theme_training_celia_pell_watch",
		"priority": 9,
		"when": { "time_block": "dawn" },
		"speaker": "Celia",
		"listener": "Pell Rowan",
		"zone_type": "watch_post",
		"preferred_visit_themes": ["training"],
		"text": "\"Again. Same call—cleaner.\" — \"Yes, Sergeant. Sorry—yes.\"",
		"once_per_visit": false,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "bark_theme_tense_sabine_veska_wall",
		"priority": 9,
		"when": { "time_block": "day" },
		"speaker": "Sabine Varr",
		"listener": "Veska Moor",
		"zone_type": "wall",
		"preferred_visit_themes": ["tense"],
		"text": "\"No heroics on my section.\" — \"Define heroics.\" — \"Anything that makes me rewrite the roster.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "bark_theme_somber_corvin_hadrien_shrine",
		"priority": 8,
		"when": { "time_block": "night" },
		"speaker": "Corvin Ash",
		"listener": "Ser Hadrien",
		"zone_type": "shrine",
		"preferred_visit_themes": ["somber"],
		"text": "\"Daylight turns guilt into theater.\" — \"Night lets you rehearse the truth without an audience.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "bark_theme_normal_oren_rufus_supply",
		"priority": 7,
		"when": { "time_block": "day" },
		"speaker": "Oren Pike",
		"listener": "Rufus",
		"zone_type": "supply",
		"preferred_visit_themes": ["normal"],
		"avoided_visit_themes": ["gossip"],
		"text": "\"Tar bucket where it belongs.\" — \"Miracle of the week.\"",
		"once_per_visit": false,
		"radius": 150.0,
		"pair_radius": 88.0,
	},
	{
		"id": "bark_theme_training_maela_inez_tree",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Maela Thorn",
		"listener": "Inez",
		"zone_type": "tree_line",
		"preferred_visit_themes": ["training"],
		"text": "\"Timer me.\" — \"If you cheat, I will hear it.\" — \"Romantic.\"",
		"once_per_visit": false,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "bark_theme_gossip_tariq_nyx_map",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Tariq",
		"listener": "Nyx",
		"zone_type": "map_table",
		"preferred_visit_themes": ["gossip", "tense"],
		"text": "\"Rumor says the pass is open.\" — \"Rumor also says salt is sugar. I checked both.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "bark_theme_hopeful_yselle_pell_bench",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Yselle Maris",
		"listener": "Pell Rowan",
		"zone_type": "bench",
		"preferred_visit_themes": ["hopeful"],
		"text": "\"You're practicing posture, not armor.\" — \"Feels the same on bad days.\" — \"Then lean on the difference.\"",
		"once_per_visit": false,
		"radius": 150.0,
		"pair_radius": 88.0,
	},
	{
		"id": "bark_theme_somber_meris_liora_infirmary",
		"priority": 8,
		"when": { "time_block": "night" },
		"speaker": "Sister Meris",
		"listener": "Liora",
		"zone_type": "infirmary",
		"preferred_visit_themes": ["somber", "recovery"],
		"text": "\"Hold the lantern steady.\" — \"I'm trying.\" — \"That is already enough.\"",
		"once_per_visit": true,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
	{
		"id": "bark_theme_training_hest_garrick_workbench",
		"priority": 8,
		"when": { "time_block": "day" },
		"speaker": "Hest \"Sparks\"",
		"listener": "Garrick Vale",
		"zone_type": "workbench",
		"preferred_visit_themes": ["training", "tense"],
		"text": "\"If this fails, it fails small.\" — \"Small failures still get filings in my office.\"",
		"once_per_visit": false,
		"radius": 150.0,
		"pair_radius": 90.0,
	},
]

static func get_all_micro_barks() -> Array:
	return MICRO_BARKS.duplicate()

static func when_matches(entry: Dictionary, context: Dictionary) -> bool:
	var when_dict: Variant = entry.get("when", {})
	if not (when_dict is Dictionary):
		pass
	else:
		for k in (when_dict as Dictionary).keys():
			var expected = (when_dict as Dictionary).get(k)
			if not context.has(k):
				return false
			if str(context.get(k)) != str(expected):
				return false
	if entry.has("moods"):
		var moods_v: Variant = entry.get("moods", [])
		if moods_v is Array:
			var want_mood: String = str(context.get("camp_mood", "normal")).strip_edges().to_lower()
			var allowed: Array = moods_v
			var matched: bool = false
			for m in allowed:
				if str(m).strip_edges().to_lower() == want_mood:
					matched = true
					break
			if not matched:
				return false
	if not _story_progress_matches(entry, context):
		return false
	return true

static func _story_progress_matches(entry: Dictionary, context: Dictionary) -> bool:
	var progress_level: int = int(context.get("progress_level", 0))
	var min_level: int = int(entry.get("min_progress_level", -1))
	if min_level >= 0 and progress_level < min_level:
		return false
	var max_level: int = int(entry.get("max_progress_level", -1))
	if max_level >= 0 and progress_level > max_level:
		return false
	var flags_v: Variant = context.get("story_flags", {})
	var story_flags: Dictionary = flags_v if flags_v is Dictionary else {}
	var req_v: Variant = entry.get("required_story_flags", [])
	if req_v is Array:
		for token_v in (req_v as Array):
			var token: String = str(token_v).strip_edges()
			if token == "":
				continue
			if not bool(story_flags.get(token, false)):
				return false
	var block_v: Variant = entry.get("blocked_story_flags", [])
	if block_v is Array:
		for token_v2 in (block_v as Array):
			var token2: String = str(token_v2).strip_edges()
			if token2 == "":
				continue
			if bool(story_flags.get(token2, false)):
				return false
	return true
