# ==============================================================================
# Script Name: DialogueDatabase.gd
# Purpose: A global repository for all camp NPC dialogue lines.
# Overall Goal: Decouple dialogue text from the UI to allow easy expansion and editing.
# Project Fit: Runs as an Autoload (Singleton).
# Dependencies: None.
# AI/Code Reviewer Guidance:
#   - Core Logic Sections: Contains dictionaries for Blacksmith and Merchant lines.
#   - Extension Points: Add new keys or strings to the dictionaries to expand dialogue.
# ==============================================================================

extends Node

var blacksmith_lines: Dictionary = {
	"welcome": [
		"The forge is hot and my hammer is heavy. What's the word, Boss?",
		"Ah, Commander! My anvil was starting to feel neglected. What are we making?",
		"Back in one piece? Good. Let's make sure your steel is in one piece too.",
		"I’d forge a shield out of my own beard if it kept you safe. Need work done?",
		"The song of the hammer is the only music I need. Ready to add a verse?"
	],
	"monologue": [
		"My old man used to say: 'Haldor, a dwarf is only as good as the temper of his steel.' I've spent fifty years trying to prove him right.",
		"They ask why I left the Great Halls. Too many kings, not enough anvils. Out here, the air is cold, but the metal is honest.",
		"You see this singe on my left braid? Dragon fire. From a young drake in the southern peaks. Didn't get the kill, but I kept the scales.",
		"The song of the hammer... it’s the only music that makes sense anymore. Every strike is a heartbeat. When I stop swinging, I suppose that’s that.",
		"Magic is all well and good for the scholars, but give me a well-balanced axe and a sturdy whetstone any day. Iron doesn't run out of mana.",
		"I've forged blades for heroes who never came home, and for villains who deserved to fall. Now, I just forge for you. Make it count, Commander.",
		"Dwarven ale is meant to be thick enough to chew. This human swill you lot drink is basically water with a bad attitude."
	],
	"craft_start": [
		"Stand back, Boss. Sparks are about to fly!",
		"A fine choice. This steel has a destiny.",
		"Focus, Haldor... only the best for the Commander."
	],
	"craft_normal": [
		"There. Solid as a mountain. It’ll serve you well.",
		"Finished! Not my greatest work, but better than anything a goblin could forge.",
		"It’s sharp, it’s balanced, and it’s yours. Go put it to use!"
	],
	"craft_masterwork": [
		"BY THE MOTHERLODE! Look at that shine! It’s... it’s beautiful.",
		"Commander, I think the gods themselves helped me strike that one!",
		"This isn't a weapon anymore. It's a legend. Give it a name worthy of its edge!",
		"My masterpiece! I'd follow you into the Abyss just to see this blade in action!"
	],
	"repair_normal": [
		"Good as new. Stop trying to break it so fast, eh?",
		"Fixed the nicks and polished the edge. She’s ready for blood again.",
		"A little oil, a little heat, and she's back in the fight."
	],
	"repair_masterwork": [
		"I didn't just fix it, Boss. I made it better. Much better.",
		"She’s tougher now than the day she was born! Try not to dent it.",
		"Masterwork repair! That steel will outlast us both now."
	],
	"salvage": [
		"Reduced to scrap. The forge takes all.",
		"A shame to break it, but we need the materials.",
		"Nothing is wasted in my forge, Boss.",
		"Torn apart and ready to be reborn!",
		"I'll break this down. We'll put it to better use."
	]
}

var merchant_lines: Dictionary = {
	"welcome": [
		"Well, %s. The road delivered you intact. Pity for my odds.",
		"Take a seat, %s. The wares are honest. The prices are not.",
		"Greetings, %s. The paladins still want my head, so speak softly.",
		"Ah, %s. I carry provisions for war, regret, and profit. Mostly profit.",
		"Welcome, %s. If your armor drips, aim away from the cloth.",
		"Step closer, %s. The donkey bites only the indecisive.",
		"You smell like battle, %s. That scent costs extra to air out.",
		"I hear the guild whispers your name, %s. I prefer coins over gossip.",
		"Come browse, %s. Everything here was acquired with minimal witness.",
		"Ah, %s. I kept your favorite shelf empty. For a fee.",
		"If you seek holy relics, %s, I carry several that have never seen a temple.",
		"Tomb dust on your boots, %s. We understand each other.",
		"The goblin markets raised my prices today, %s. Blame their enthusiasm.",
		"Welcome, %s. I offer steel, salves, and moral ambiguity.",
		"Back from the dead again, %s. My ledger hates surprises.",		
		"Back already, %s? My prices are high, but my standards are... questionable.",
		"Ah, the legendary %s. Please, buy something. My donkey is very hungry.",
		"Looking for steel, %s? Or perhaps a very shiny spoon? I have both.",
		"Stay a while and listen, %s. Or just give me your gold. Mostly the gold.",
		"I've traveled from Val-d'Or just to sell you this junk, %s. Don't let me down.",
		"The battlefield looks rough, %s. Lucky for you, greed is my primary motivator.",
		"Welcome back, %s. Try not to bleed on the merchandise this time.",
		"Ah, %s. I was just wondering who would fund my early retirement.",
		"Do come in, %s. The guild thinks I am dead, so let us keep this transaction quiet.",
		"I have goods from the far reaches of the abyss, %s. And also some very mediocre boots.",
		"Greetings, %s. If the authorities ask, we have never met.",
		"You survived, %s. Frankly, I had already started marking up your reserved gear.",
		"Step right up, %s. I have exactly what you need to delay your inevitable demise.",
		"Ah, %s. Still breathing, I see. How terribly inconvenient for my betting pool.",
		"Welcome, %s. Please lower your voice, the cursed amulets are trying to sleep.",
		"I see you brought your coin purse, %s. Let us relieve you of that heavy burden."
	],
	"buy": [
		"Sold, %s. If it screams at night, sleep farther away.",
		"A wise purchase, %s. The previous owner stopped complaining eventually.",
		"Keep the wax mark, %s. It proves you overpaid.",
		"Fine choice, %s. I polished it with a very clean prayer.",
		"Spend freely, %s. The war will not refund you.",
		"Take it, %s. May it wound your foes more than it wounds your purse.",
		"A pleasant exchange, %s. My donkey approves of the weight.",
		"Good, %s. One less cursed trinket for me to babysit.",
		"Excellent, %s. I can now afford silence from the guild.",
		"Hold it firmly, %s. Some artifacts prefer to be carried, not owned.",
		"May it serve you, %s. If it does not, I never met you.",
		"A bold buy, %s. Boldness and coin often travel together.",
		"You have taste, %s. Tragic, expensive taste.",
		"There. Yours, %s. Try not to wake whatever is sleeping inside it.",
		"Thank you, %s. I shall invest this gold in distance.",		
		"A fine choice, %s. That was almost a family heirloom.",
		"Careful with that, %s. It's sharp. I think.",
		"A pleasure doing business. Tell your friends (if they're rich), %s.",
		"This item has a 100%% guarantee. (Guarantee void upon leaving the camp, %s.)",
		"Sold. You've got an eye for quality, %s. Or at least for things that glow.",
		"An excellent choice, %s. I looted that from a very prestigious corpse.",
		"Consider it yours, %s. No refunds if it spontaneously combusts.",
		"A wise investment, %s. Or at least, a very profitable one for me.",
		"I will miss that one, %s. It doubled as a decent back scratcher.",
		"Sold to %s. May it serve you better than it served its previous, much deader owner.",
		"Thank you, %s. I can finally pay off that bounty hunter.",
		"You have exquisite taste, %s. And remarkably deep pockets.",
		"It is yours, %s. I accept no liability for any curses, hexes, or minor hauntings.",
		"Marvelous, %s. I was wondering how to get rid of that without alerting the guards.",
		"A transaction wrapped in mutual respect, %s. Mostly respect for your gold."
	],
	"sell": [
		"Let me see that, %s. It looks like it survived you by accident.",
		"I will buy it, %s. Not because it has worth, but because it has a market.",
		"Is that a paladin seal, %s. Interesting. I will pay extra to forget it.",
		"Fine, %s. The goblins will love it, or eat it. Either way, profit.",
		"I will take this off your hands, %s. Your hands will thank me.",
		"This reeks of tomb wards, %s. I charge a handling fee in my heart.",
		"Very well, %s. I know a dwarf who asks no questions and counts quickly.",
		"You call it loot, %s. I call it inventory.",
		"I will offer you a fair price, %s. Fair to me.",
		"Hand it over, %s. I have fenced worse to saints with clean hands.",
		"This blade has stories, %s. I will sell it as a legend and pay you as scrap.",
		"I will buy it, %s. If anyone asks, you found it in a river.",
		"All right, %s. I will add it to the pile marked regrettable.",
		"Hmm, %s. Bloodstains add character, and character adds coin.",
		"Deal, %s. Your trash becomes my doctrine.",		
		"You want me to pay for this, %s? Fine, but I'm losing money here.",
		"Ooh, slightly used. I can work with this, %s.",
		"I'll give it a new home. Or melt it down. Probably melt it down, %s.",
		"Is this blood, %s? Never mind, don't tell me. I'll just double the cleaning fee.",
		"I'll take it off your hands, %s. It'll make a great paperweight.",
		"I suppose I can take this, %s. The goblin market is remarkably forgiving.",
		"Are you sure, %s. This looks suspiciously like evidence.",
		"Hand it over, %s. I know a wizard who buys absolute garbage.",
		"I will give you half its value, %s. And consider it a personal favor.",
		"You bring me such curious trash, %s.",
		"Fine, %s. I will put it with the other things nobody wants.",
		"If you insist, %s. But I will need to wash my hands after touching this.",
		"I am buying this purely out of pity, %s.",
		"Let us just toss this in the bargain bin, %s. Right next to my hopes and dreams.",
		"Very well, %s. I have fenced worse things to better people."
	],
	"poor": [
		"Your purse sounds hollow, %s. My donkey finds that unsettling.",
		"No coin, %s. No miracles.",
		"I trade in gold, %s. Not good intentions.",
		"That offer would shame a goblin, %s.",
		"If you cannot pay, %s, at least stop breathing on the inventory.",
		"Come back richer, %s. Preferably alive.",
		"I have seen beggars with fuller purses, %s.",
		"If you insist on poverty, %s, do it elsewhere.",
		"I do not accept vows, %s. The last paladin tried, and it tasted like air.",
		"The guild taught me many things, %s. Charity was not among them.",
		"Your gold is missing, %s. I notice such tragedies.",
		"Try the temple, %s. They hand out blessings, not blades.",
		"You could always rob a tomb, %s. I hear it builds character.",
		"My donkey charges interest, %s. He starts by biting.",
		"Return when you can afford regret, %s.",		
		"Gold, my friend. I need the shiny yellow stuff. Not promises, %s.",
		"I'm a merchant, not a charity, %s. Come back when you're wealthier.",
		"That's a lot of window shopping for someone with empty pockets, %s.",
		"I cannot accept lint as payment, %s.",
		"Your lack of funds is deeply offensive to my religion, %s.",
		"Perhaps try looting more efficiently, %s.",
		"I am running a business, %s, not a refuge for the financially inept.",
		"Come back when your purse matches your ambition, %s.",
		"Are you trying to pay me in exposure, %s. Because that does not feed the donkey.",
		"Your gold count is as tragic as your fashion sense, %s.",
		"Please step aside, %s. You are blocking the paying customers. Oh wait, there are none.",
		"I would offer you a loan, %s, but I enjoy my kneecaps exactly where they are.",
		"This is a shop, %s. You give me gold, I give you items. It is a very simple concept."
	],
	"haggle_win": [
		"Fine, %s. I will shave the price, not my beard.",
		"You win, %s. My margins limp away.",
		"All right, %s. The donkey will eat less and judge you more.",
		"Very well, %s. Tell no one you saw weakness in me.",
		"A discount, %s. I hope it keeps you warm at night.",
		"You negotiated like a dwarf in a closed mine, %s.",
		"There. Lowered, %s. My scribe just fainted somewhere.",
		"Take your victory, %s. I will recover in the next transaction.",
		"Price reduced, %s. My grudges remain full price.",
		"I concede, %s. Your tongue is sharper than your steel.",
		"All right, %s. I will call it a loyalty reward for not dying.",
		"Fine, %s. I will pretend this was my idea.",
		"Discount granted, %s. The guild will hear a different story.",
		"You have talent, %s. It is wasted on heroism.",
		"Agreed, %s. The coin still shines, even when fewer.",
		"Alright, alright, %s. You drive a hard bargain. I'll lower my margins... slightly.",
		"You're robbing me blind, %s. But fine, your reputation precedes you.",
		"Fine, %s. Take it for less. I will just skip dinner tonight.",
		"You are a ruthless negotiator, %s. My donkey will go hungry because of you.",
		"Very well, %s. Consider this a discount for your highly intimidating aura.",
		"I concede, %s. You haggle like a dwarven debt collector.",
		"A lower price, as requested, %s. Please do not tell the Merchants Guild.",
		"You win this round, %s. I hope you feel proud of swindling a humble man.",
		"Discount applied, %s. Let the record show I protested vehemently.",
		"Alright, %s. But I expect a glowing recommendation to the next wealthy traveler.",
		"Take it, %s. Just take it and leave me to my sorrow.",
		"You have beaten me down, %s. I am emotionally and financially ruined."
	],
	"haggle_lose": [
		"No, %s. I have standards, and they cost money.",
		"Your argument is stirring, %s. My price remains unmoved.",
		"Try again after you defeat a dragon, %s. Dragons pay better.",
		"I refuse, %s. The donkey says your offer is weak.",
		"That was adorable, %s. The number stays the same.",
		"My prices are carved in stone, %s. Dwarven stone.",
		"You may bargain with goblins, %s. I charge for dignity.",
		"Not today, %s. I enjoy eating.",
		"If I lower it, %s, the paladins might think I have a heart.",
		"No discount, %s. I already risked my neck acquiring it.",
		"Your haggling lacks venom, %s. The guild would be disappointed.",
		"Keep your coin ready, %s. You will need all of it.",
		"I have heard worse offers in a graveyard, %s.",
		"My answer stays no, %s. Repetition only increases the price.",
		"Haggle all you like, %s. The number will not flinch.",
		"Nice try, %s. But Bartholomew The Bold does not fold so easily.",
		"Stick to fighting, %s. Leave the economics to the professionals.",
		"I admire your audacity, %s, but my prices are as fixed as my moral compass.",
		"Absolutely not, %s. I have a bounty to pay off.",
		"You cannot charm me, %s. I left my heart in a tavern in Val-d'Or.",
		"Try that again, %s, and I will start charging you for breathing my air.",
		"Did you really think that would work on me, %s.",
		"No discount for you, %s. In fact, I am tempted to charge a loitering fee.",
		"My donkey negotiates better than you do, %s.",
		"Do I look like a philanthropist, %s. The price remains.",
		"I would rather throw it in the river than sell it for that, %s.",
		"A tragic attempt at bartering, %s. Stick to swinging your weapon."
	],
	"haggle_mid": [
		"You are warming up, %s. My patience is not infinite, but it is theatrical.",
		"Halfway there, %s. The donkey is taking notes.",
		"Steady, %s. I respect a buyer who can hover.",
		"Interesting rhythm, %s. Are you negotiating or conducting an orchestra?",
		"You have focus, %s. That is almost as valuable as coin.",
	],
	"haggle_concede": [
		"Fine, %s. Walk away. I will pretend this never tested my nerves.",
		"Go, %s. My ledger will not mourn what you did not buy.",
		"As you wish, %s. The price remains, and my opinion of you is merely confused.",
		"Leaving mid-dance, %s. How very diplomatic.",
		"No harm done, %s. Next time bring steadier hands or heavier coin.",
	],
	"haggle_win_extra": [
		"And %s — I will mark a second shelf item down before I regret it. Do not make me say it twice.",
		"You broke me twice today, %s. Another piece joins the half-price pile. Happy?",
		"Fine, %s. Two discounts. The guild will assume I was hit on the head.",
		"Take your victory lap, %s. A second trinket goes on sale before I come to my senses.",
	],
	"idle": [
		"Are you going to buy something, %s, or just stare at my magnificent beard.",
		"I once sold a half-eaten apple to a king. True story, %s.",
		"It is quiet today... too quiet. Buy a sword, %s, just in case.",
		"Did I mention these prices are a steal, %s. Because I might have stolen some of this.",
		"Take your time, %s. It is not like I have other customers.",
		"I was not always a merchant, %s. The Guild of Assassins simply had a terrible pension plan.",
		"They say I was born from a dragon's hoard, %s. The truth involves far more paperwork and a very angry dwarven king.",
		"This monocle is not for show, %s. Staring into the abyss is quite bad for one's depth perception.",
		"Do not ask how I acquired the Archmage's spare slippers, %s. Plausible deniability is my greatest ware.",
		"My donkey is named after my first commanding officer, %s. They share the same stubbornness and smell.",
		"The Paladins of the Silver Hand are currently looking for me, %s. If they ask, I am merely a humble turnip farmer.",
		"I fought in the Siege of the Black Citadel, %s. Well, I sold overpriced bandages to the survivors, which is basically the same thing.",
		"Some call it grave robbing, %s. I prefer the term archaeological liquidation.",
		"I learned the art of the deal in the deep mines of Val-d'Or, %s. The goblins down there drive a very hard bargain.",
		"If you perish in the next battle, %s, do you mind if I reclaim my merchandise.",
		"My donkey is staring at you, %s. He only judges the guilty.",
		"I once smuggled dwarven silver through a monastery, %s. The monks were excellent customers.",
		"Do not touch the black ring, %s. It touches back.",
		"The guild sent me a letter once, %s. It was mostly threats and poor spelling.",
		"If you need a paladin, %s, try the next valley. I sell them rope and lies.",
		"Some heroes chase glory, %s. I chase debts that multiply.",
		"The goblin market taught me that morals are negotiable, %s.",
		"I can smell cursed silver, %s. It smells like opportunity.",
		"If a tomb whispers your name, %s, you should answer with a shovel. I did.",
		"That scar on my neck, %s. A paladin tried to collect what I owed.",
		"The donkey prefers oats, %s. I prefer your coin. We compromise poorly.",
		"I keep my daggers for cutting rope now, %s. Mostly.",
		"Every artifact here has a history, %s. Some also have a temper.",
		"If the war ends tomorrow, %s, I will sell mourning cloaks by sunset.",
		"Take your time, %s. I am only counting how long it takes you to surrender your gold."	
	]
}

var talk_lines: Dictionary = {
	"idle_open": [
		"What do you want, {name}. Time is money.",
		"Speak, {name}. The donkey charges me for loitering.",
		"If you are here to browse, {name}, at least look expensive.",
		"You have that heroic stare, {name}. It usually precedes unpaid invoices.",
		"Keep it brief, {name}. My profit margin is on a tight leash.",
		"If the paladins appear, {name}, you saw a turnip farmer.",
		"I have wares and a questionable conscience, {name}. Choose quickly.",
		"The war drags on, {name}. My prices keep pace.",
		"My tent is open, {name}. My trust is not.",
		"Ask for work or rumors, {name}. Small talk costs extra.",
		"Do not touch anything glowing, {name}. Unless you plan to buy it.",
		"I am listening, {name}. Mostly for coin clinking.",
		"You again, {name}. The guild would call this persistence.",
		"If you need a blessing, {name}, try a chapel. I sell outcomes.",
		"I have a schedule, {name}. It begins with payment."
	],
	"quest_waiting": [
		"I am still waiting on {amount} {item}{plural}, {name}. The donkey keeps count better than you.",
		"Bring me {amount} {item}{plural}, {name}. Preferably not soaked in blood this time.",
		"My ledger says {amount} {item}{plural}, {name}. The ledger rarely lies, unlike people.",
		"You owe me {amount} {item}{plural}, {name}. I would settle for speed, but coin will do.",
		"I require {amount} {item}{plural}, {name}. The tombs will not rob themselves.",
		"Still collecting {amount} {item}{plural}, {name}. Try the goblin stalls if you are desperate.",
		"The contract remains {amount} {item}{plural}, {name}. I wrote it in ink and spite.",
		"Deliver {amount} {item}{plural}, {name}. I have buyers who do not ask questions.",
		"I want {amount} {item}{plural}, {name}. If you bring fewer, you bring disappointment.",
		"Do you have my {amount} {item}{plural}, {name}. My patience has a shorter lifespan than you.",
		"Find {amount} {item}{plural}, {name}. The guild expects results, and so do I.",
		"I am paying for {amount} {item}{plural}, {name}. Do not make me look charitable.",
		"{amount} {item}{plural}, {name}. That is the whole job. Try not to improve it.",
		"You will return with {amount} {item}{plural}, {name}. Or you will return empty, which is worse.",
		"I am still missing {amount} {item}{plural}, {name}. The war ends faster than your errands."
	],
	"quest_short": [
		"Do not waste my time. You have {found} of {amount} {item}{plural}.",
		"Count with me. {found} of {amount} {item}{plural}. You are not done.",
		"You brought {found}. I asked for {amount} {item}{plural}. Try again.",
		"I see {found} in your pack. I require {amount} {item}{plural}.",
		"So far, {found} of {amount} {item}{plural}. My donkey looks unimpressed.",
		"{found} does not equal {amount}. Neither does wishful thinking. Bring {item}{plural}.",
		"You are short. {found} of {amount} {item}{plural}. That is arithmetic, not an insult.",
		"If you cannot reach {amount} {item}{plural}, stop bringing me {found} and excuses.",
		"The guild would laugh. {found} of {amount} {item}{plural}. I am close to joining them.",
		"You are nearly competent. {found} of {amount} {item}{plural}. Do not ruin it now.",
		"I can sell {found}. I can pay for {amount}. Finish the job.",
		"I will not pay full reward for {found} of {amount} {item}{plural}. I am greedy, not confused.",
		"{found} of {amount}. Bring the rest of the {item}{plural} before the trail goes cold.",
		"I am still missing {missing} {item}{plural}. You keep returning with {found}.",
		"This is a collection job, not a heroic tale. {found} of {amount} {item}{plural}."
	],
	"quest_complete": [
		"Excellent. Here is your {reward} gold, {name}. Spend it before someone braver takes it.",
		"Good. {reward} gold, {name}. Your competence has been noted, briefly.",
		"Payment delivered. {reward} gold, {name}. Do not make me regret accuracy.",
		"Here. {reward} gold, {name}. The donkey approves of punctual labor.",
		"You delivered. I pay. {reward} gold, {name}. That is the only romance I tolerate.",
		"{reward} gold, {name}. If you tell anyone I paid fairly, I will deny it.",
		"Well done. {reward} gold, {name}. The guild will be pleased. I will be richer.",
		"Take {reward} gold, {name}. Try not to die with it unspent.",
		"{reward} gold, {name}. I will now pretend you were never in debt.",
		"A clean delivery. {reward} gold, {name}. As clean as business gets.",
		"You have earned {reward} gold, {name}. I am mildly annoyed by your success.",
		"{reward} gold, {name}. Next time I will ask for something harder, to restore balance.",
		"Here is {reward} gold, {name}. I will reinvest my gratitude into more profit.",
		"{reward} gold, {name}. The paladins would call this blood money. I call it money.",
		"Take {reward} gold, {name}. Then leave before I start offering a bonus."
	],
	"abandon": [
		"A shame, {name}. I will hire someone less heroic and more reliable.",
		"Fine, {name}. I will find a goblin with lower standards.",
		"You withdraw, {name}. My ledger will survive. Your reputation may not.",
		"Understood, {name}. Do not expect me to remember you fondly, or at all.",
		"So be it, {name}. I will sell your promise at a discount.",
		"Leaving empty-handed, {name}. A bold strategy for someone who likes breathing.",
		"Very well, {name}. I will assign the work to my donkey. He at least shows up.",
		"You abandon the job, {name}. The guild loves that sort of tragedy.",
		"I accept your surrender, {name}. It costs nothing, which suits you.",
		"Fine, {name}. I will recover my losses by raising prices. On you.",
		"Then we are done, {name}. Do not return expecting warm words.",
		"Quit if you must, {name}. I will remember this at the bargaining table.",
		"All right, {name}. Someone else will loot the tombs and take the credit.",
		"As you wish, {name}. Try not to waste my time twice.",
		"Go, {name}. My patience is a finite resource and you have spent it."
	],
	"rumors": [
		"Rumor says the duke hired paladins to cleanse the old road, {name}. They mostly cleanse travelers of coin.",
		"They say goblins are selling blessed arrows this week, {name}. The blessing is usually a lie.",
		"A tomb near the Black Fen reopened, {name}. It also reclosed. On a party.",
		"The Silver Hand is hunting a merchant with a monocle, {name}. Terrible description, truly.",
		"A witch in the pines buys battlefield teeth, {name}. I do not ask why. I only ask the price.",
		"Word is a necromancer is paying in rubies, {name}. The rubies scream less than the corpses.",
		"The dwarven mines are sealed again, {name}. Smugglers are already celebrating.",
		"A cursed chalice surfaced in the river, {name}. Everyone who drank from it became honest for a day.",
		"A bandit lord is collecting banners, {name}. Apparently cloth has a market now.",
		"The archmage mislaid a staff, {name}. Half the realm is searching. I already priced it.",
		"A paladin relic was sold in a goblin market, {name}. The paladins pretend not to know.",
		"They say the king is afraid of donkeys, {name}. Sensible man, in my experience.",
		"There is a shrine that grants luck for a tithe, {name}. The priest keeps the luck.",
		"A caravan vanished near the old watchtower, {name}. Survivors report polite skeletons.",
		"Someone is forging guild seals again, {name}. I respect the craft, not the competition."
	]
}

var blacksmith_monologues = [
	# --- EARLY GAME (Always available) ---
	{"unlock_level": 0, "text": "My old man used to say: 'Haldor, a dwarf is only as good as the temper of his steel.' I've spent fifty years trying to prove him right."},
	{"unlock_level": 0, "text": "They ask why I left the Great Halls. Too many kings, not enough anvils. Out here, the air is cold, but the metal is honest."},
	{"unlock_level": 0, "text": "Dwarven ale is meant to be thick enough to chew. This human swill you lot drink is basically water with a bad attitude."},
	
	# --- MID GAME (Unlocks after beating Map 2) ---
	{"unlock_level": 2, "text": "You survived the lower valleys, eh? Good. The enemies ahead wear thicker armor. We'll need to strike hotter."},
	{"unlock_level": 2, "text": "I saw the dents in your shields from the last skirmish. Sloppy footwork! Let the shield take the glance, not the brunt."},
	
	# --- LATE GAME (Unlocks after beating Map 4) ---
	{"unlock_level": 4, "text": "You see this singe on my left braid? Dragon fire. From a drake in the southern peaks. Didn't get the kill, but I kept the scales."},
	{"unlock_level": 4, "text": "The ores you're bringing back... they carry a strange chill. Dark magic is stirring, Commander."},
	
	# --- END GAME (Unlocks after beating Map 7) ---
	{"unlock_level": 7, "text": "I've forged blades for heroes who never came home, and for villains who deserved to fall. Now, I just forge for you. Make it count."},
	{"unlock_level": 7, "text": "The song of the hammer... it’s the only music that makes sense anymore. Every strike is a heartbeat. Let's make 'em beat loud."}
]
